### ISSUE TITLE
Oracle Table Name Mapping Perf

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#1195]
It seems like the following codepath hits a part of the new oracle table name mapping magics that should be behind a cache/supplier, but appears not to be; if it is indeed not, it is a sizable perf regression.

Snippet of my stacktrace:
```
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ConnectionSupplier.getFresh(ConnectionSupplier.java:49) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ConnectionSupplier.get(ConnectionSupplier.java:38) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.OracleTableNameUnmapper.getShortTableNameFromMappingTable(OracleTableNameUnmapper.java:37) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.OracleTableNameGetter.getInternalShortTableName(OracleTableNameGetter.java:58) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.PrefixedTableNames.getOraclePrefixedTableName(PrefixedTableNames.java:45) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.PrefixedTableNames.get(PrefixedTableNames.java:36) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getPrefixedTableName(DbKvsGetRanges.java:333) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getSimpleRowSelectOneQueryOracle(DbKvsGetRanges.java:326) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getRangeQueryAndArgs(DbKvsGetRanges.java:199) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getFirstPages(DbKvsGetRanges.java:107) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getFirstBatchForRanges(DbKvsGetRanges.java:94) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs.getFirstBatchForRanges(DbKvs.java:384) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getFirstBatchForRanges(ForwardingKeyValueService.java:129) ~[atlasdb-client/:na]
```

**Comment by clockfort** [comment]
It also appears as if the connection created here is not properly closed

**Comment by jboreiko** [comment]
@hsaraogi is not working today but I will be sure to get her input here ASAP.  From my understanding she is aware of the lack of caching but likely not of the dangling connections.

**Comment by hsaraogi** [comment]
Digging into the call hierarchy, I found that the connectionSupplier for `DbKvsGetRanges` is passed in from `Dbkvs#getFirstBatchForRanges` and will be closed at `Dbkvs#close`. If we close the connectionSupplier after the lookup for `ORACLE_TABLE_MAPPING`, the supplier will no longer be usable for other `Dbkvs` calls.

**Comment by hsaraogi** [comment]
We are aware of the absence of caching over table name and are tracking this as part of Oracle perf benchmarking.

**Comment by schlosna** [comment]
I don't think we can bump internal dependencies to pick this up until this is fixed as it will kill throughput with extra DB round trips, which is why I flagged it in the initial PR https://reviewable.io/reviews/palantir/atlasdb/1076#-KUI3Jn3gpJUp-1tXp5D-r1-81

**Comment by clockfort** [comment]
Right now, the code causes anyone who calls getFirstBatchForRanges to get thousands of error messages from CloseTracking.java because the connection that it gets is closed on deref rather than manually.

I think the easiest place to see the issue is here (I added two comments inline):

```
    private Map<RangeRequest, TokenBackedBasicResultsPage<RowResult<Value>, byte[]>> getFirstPages(
            TableReference tableRef,
            List<RangeRequest> requests,
            long timestamp) {
        List<String> subQueries = Lists.newArrayList();
        List<Object> argsList = Lists.newArrayList();
        for (int i = 0; i < requests.size(); i++) {
            RangeRequest request = requests.get(i);
            Pair<String, List<Object>> queryAndArgs = getRangeQueryAndArgs( // <-- this is the codepath we're in that opens a connection in the table mapper and doesn't close it before CloseTracking.java notices it's dereferenced
                    tableRef,
                    request.getStartInclusive(),
                    request.getEndExclusive(),
                    request.isReverse(),
                    request.getBatchHint() == null ? 1 : request.getBatchHint(),
                    i);
            subQueries.add(queryAndArgs.lhSide);
            argsList.addAll(queryAndArgs.rhSide);
        }
        String query = Joiner.on(") UNION ALL (").appendTo(new StringBuilder("("), subQueries).append(")").toString();
        Object[] args = argsList.toArray();

        TimingState timer = logTimer.begin("Table: " + tableRef.getQualifiedName() + " get_page");
        final SqlConnection conn = connectionSupplier.get();
        try {
            return getFirstPagesFromDb(tableRef, requests, timestamp, conn, query, args); // <-- this is the normal codepath that opens a connection and does close it manually / correctly
        } finally {
            closeSql(conn);
            timer.end();
        }
    }
```
