### ISSUE TITLE
Partitioned Timelock Leader Returns 500s

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1241]
1. Start with a cluster of timelock servers.
2. Build a client (a remote proxy with failover), using the timelock leader as the first URI in the list.
3. Partition off the leader, so that it cannot send nor receive packets from any other node.
4. The client fails to give you a timestamp, because the old leader returns a 500.

To fix this we either need to treat 500 as retryable or to have the old leader return a 503 in this scenario.

**Comment by SerialVelocity** [comment]
Yep, that's just a bug in the current implementation. Going to fix that today.

**Comment by SerialVelocity** [comment]
Can you post the 500 error stacktrace?

**Comment by SerialVelocity** [comment]
<details><summary>**Stack trace**</summary><p>
```
ERROR [2016-11-18 11:46:19,809] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: ad79383c2265ccf0
! java.net.ConnectException: failed to connect
! at io.atomix.copycat.client.util.ClientConnection.sendRequest(ClientConnection.java:126) ~[atomix-all-1.0.0-rc9.jar:na]
! at io.atomix.copycat.client.util.ClientConnection.lambda$handleResponse$11(ClientConnection.java:148) ~[atomix-all-1.0.0-rc9.jar:na]
! at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_111]
! at io.atomix.copycat.client.util.ClientConnection.connect(ClientConnection.java:204) ~[atomix-all-1.0.0-rc9.jar:na]
! at io.atomix.copycat.client.util.ClientConnection.handleConnection(ClientConnection.java:220) ~[atomix-all-1.0.0-rc9.jar:na]
! at io.atomix.copycat.client.util.ClientConnection.lambda$connect$18(ClientConnection.java:208) ~[atomix-all-1.0.0-rc9.jar:na]
! at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_111]
! at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[na:1.8.0_111]
! at io.atomix.catalyst.transport.netty.NettyClient.lambda$null$0(NettyClient.java:100) ~[atomix-all-1.0.0-rc9.jar:na]
! at io.atomix.catalyst.concurrent.ThreadContext.lambda$execute$1(ThreadContext.java:151) ~[atomix-all-1.0.0-rc9.jar:na]
! at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$2(Runnables.java:20) ~[atomix-all-1.0.0-rc9.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_111]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_111]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
! ... 1 common frames omitted
! Causing: com.google.common.util.concurrent.UncheckedExecutionException: java.net.ConnectException: failed to connect
! at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1525) ~[guava-18.0.jar:na]
! at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1511) ~[guava-18.0.jar:na]
! at com.palantir.atlasdb.timelock.atomix.InvalidatingLeaderProxy.getLeaderId(InvalidatingLeaderProxy.java:91) ~[atlasdb-timelock-server-0.23.0-beta+003-97-g305c946.dirty.jar:na]
! at com.palantir.atlasdb.timelock.atomix.InvalidatingLeaderProxy.isLeader(InvalidatingLeaderProxy.java:83) ~[atlasdb-timelock-server-0.23.0-beta+003-97-g305c946.dirty.jar:na]
! at com.palantir.atlasdb.timelock.atomix.InvalidatingLeaderProxy.handleInvocation(InvalidatingLeaderProxy.java:67) ~[atlasdb-timelock-server-0.23.0-beta+003-97-g305c946.dirty.jar:na]
! at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-18.0.jar:na]
! at com.sun.proxy.$Proxy39.getTimeService(Unknown Source) ~[na:na]
! at com.palantir.atlasdb.timelock.TimeLockResource.getTimeService(TimeLockResource.java:42) ~[atlasdb-timelock-server-0.23.0-beta+003-97-g305c946.dirty.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
! at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter$1.run(SubResourceLocatorRouter.java:158) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.getResource(SubResourceLocatorRouter.java:178) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.apply(SubResourceLocatorRouter.java:109) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [jersey-container-servlet-core-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [jersey-container-servlet-core-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [jersey-container-servlet-core-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [jersey-container-servlet-core-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) [jersey-container-servlet-core-2.22.1.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dropwizard-jetty-0.9.3.jar:0.9.3]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:301) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132) [dropwizard-jetty-0.9.3.jar:0.9.3]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [dropwizard-servlets-0.9.3.jar:0.9.3]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [dropwizard-jersey-0.9.3.jar:0.9.3]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [dropwizard-jersey-0.9.3.jar:0.9.3]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [metrics-jetty9-3.1.1.jar:3.1.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.9.3.jar:0.9.3]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [jetty-io-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.17.v20160517.jar:9.2.17.v20160517]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.17.v20160517.jar:9.2.17.v20160517]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
10.0.42.1 - - [18/Nov/2016:11:46:16 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 500 110 "-" "okhttp/2.5.0" 2908
```
</p></details>
