### ISSUE TITLE
Timelock Server does not handle ClosedSessionException

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1280]
We don't presently have a strategy to recover from lost client sessions. To quote Atomix Javadoc (`RecoveryStrategies.java`), "when clients fail to contact a server for more than their session timeout, the client's session must be closed as linearizability is lost". This is _usually_ not a problem even if a single node gets partitioned off, because in our Timelock Server all clients are servers.

However, it is not impossible to trigger this. Consider a case where local processes are starved of CPU cycles (easy way of simulating this is to suspend your machine; I believe this is what happened when @harrybiddle encountered this), and your session gets invalidated. Then, if you are unlucky enough to have any in-flight Atomix requests, they will fail with a `ClosedSessionException` (which is correct behaviour), and this gets propagated because we use `Futures.getUnchecked(...)`.

It should probably suffice to, in the event of failure here, to simply retry the request as is with the new state; we only care pretty much about the current state of the variables. Unfortunately we do have a lot of `getUnchecked` calls. Probably the best way is to replace these `getUnchecked()`s with retry logic (I can implement a simple static method; there should be libraries as well).

Off the cuff you could probably write something like

```java
    public static DistributedLong getTimestampForClient(Atomix atomix, String client) {
        return atomix.getLong("atlasdb/timestamp/" + client)
                .exceptionally(e -> getTimestampForClient(atomix, client))
                .join();
    }
```

but it's still nasty, and also leaves the number of retries unbounded (well, bounded by your stack).

---

@harrybiddle came across this in his testing:

```java
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: io.atomix.copycat.session.ClosedSessionException: session closed
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1525)
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1511)
	at com.palantir.atlasdb.timelock.atomix.DistributedValues.getLeaderInfo(DistributedValues.java:31)
	at com.palantir.atlasdb.timelock.TimeLockServer.run(TimeLockServer.java:70)
	at com.palantir.atlasdb.timelock.TimeLockServer.run(TimeLockServer.java:48)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at com.palantir.atlasdb.timelock.TimeLockServer.main(TimeLockServer.java:52)
Caused by: io.atomix.copycat.session.ClosedSessionException: session closed
	at io.atomix.copycat.client.session.ClientSessionSubmitter.close(ClientSessionSubmitter.java:159)
	at io.atomix.copycat.client.session.ClientSession.close(ClientSession.java:193)
	at io.atomix.copycat.client.DefaultCopycatClient.recover(DefaultCopycatClient.java:246)
	at io.atomix.copycat.client.RecoveryStrategies$2.recover(RecoveryStrategies.java:48)
	at io.atomix.copycat.client.DefaultCopycatClient.onStateChange(DefaultCopycatClient.java:152)
	at io.atomix.copycat.client.session.ClientSessionState$1.accept(ClientSessionState.java:122)
	at io.atomix.copycat.client.session.ClientSessionState$1.accept(ClientSessionState.java:119)
	at io.atomix.copycat.client.session.ClientSessionState.lambda$setState$7(ClientSessionState.java:107)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at io.atomix.copycat.client.session.ClientSessionState.setState(ClientSessionState.java:107)
	at io.atomix.copycat.client.session.ClientSessionManager.lambda$keepAlive$25(ClientSessionManager.java:145)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.atomix.copycat.client.util.ClientConnection.handleResponse(ClientConnection.java:146)
	at io.atomix.copycat.client.util.ClientConnection.lambda$sendRequest$9(ClientConnection.java:124)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.atomix.catalyst.transport.netty.NettyConnection.lambda$handleResponseSuccess$5(NettyConnection.java:207)
	at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$2(Runnables.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 ```

There is no data corruption (this fails very fast) and a simple workaround is to restart the Timelock Server. However, this is inconvenient for users and should really be fixed.

**Comment by jeremyk-91** [comment]
Fixed in #1291.
