### ISSUE TITLE
better handling of concurrent queries on oracle during truncates

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#1573]
Internal tests occasionally bubble up errors when Oracle can't grab the table lock to do a truncate; probably means that someone was trying to do concurrently do writes or some other operation that takes out (oracle level) row or table locks against the table we're trying to truncate (transactions table in this case, for resetting a test).
It's also possible that we're re-using the same session that just did writes against this table and then issuing the truncate with it? Which may mean we're blocking ourselves with our own locks? It's not possible for me to further debug the problem that occurred in this previous test run, so I can't say for sure which of any of these situations occurred.

Atlas should fix:
- Throwing a misleading top-level error (in this case the error is that the table _does_ exist, and someone else is concurrently touching it)
- Not handling ORA-00054 very nicely; could maybe catch these specifically and maybe try to do a commit first and then re-attempt (if row locks were from this shared session?) and maybe have timeout/retry, or retry as a KVS.deleteRange to avoid the need for this table lock
- Harder to do, but it'd be really swell for debugging for atlas when it sees an ORA-00054 to grab the right parts of V$SESSIONS // V$LOCKS // V$SQLTEXT and log into the exception whomever the offending conflicting locks belong to / what SQL they're running

```
java.lang.IllegalStateException: Truncate called on a table (pt_met__transactions) that did not exist
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.oracle.OracleDdlTable.truncate(OracleDdlTable.java:189)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs$11.apply(DbKvs.java:1028)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs$11.apply(DbKvs.java:1025)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs.runDdl(DbKvs.java:1198)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs.truncateTable(DbKvs.java:1025)
	at com.palantir.atlasdb.keyvalue.impl.TableSplittingKeyValueService.truncateTable(TableSplittingKeyValueService.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.proxy.util.ProxyUtils.invokeAndUnwrapITEs(ProxyUtils.java:34)
	at com.palantir.profiler.ProfilingProxy.invoke(ProfilingProxy.java:39)
	at com.sun.proxy.$Proxy63.truncateTable(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.truncateTable(ProfilingKeyValueService.java:409)
	at com.palantir.atlasdb.keyvalue.impl.SweepStatsKeyValueService.truncateTable(SweepStatsKeyValueService.java:124)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.truncateTable(ForwardingKeyValueService.java:160)
	at com.palantir.metropolis.keyvalue.impl.ChronicleKeyValueService.truncateTable(ChronicleKeyValueService.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.common.proxy.AbstractDelegatingInvocationHandler.invoke(AbstractDelegatingInvocationHandler.java:26)
	at com.palantir.common.proxy.Metrics.invoke(Metrics.java:118)
	at com.sun.proxy.$Proxy63.truncateTable(Unknown Source)
	at com.palantir.atlasdb.transaction.impl.TransactionTables.truncateTables(TransactionTables.java:36)
	at com.palantir.nexus.db.AtlasConnector.clearAtlasTables(AtlasConnector.java:327)
	at com.palantir.nexus.db.AtlasConnector.clearAndTeardown(AtlasConnector.java:269)
	at com.palantir.nexus.db.MetropolisPR.resetMetropolis(MetropolisPR.java:64)
	at com.palantir.metropolis.MetropolisTestUtils.resetMetropolis(MetropolisTestUtils.java:27)
        <SNIP>
Caused by: com.palantir.exception.PalantirSqlException: While attempting to execute the SQL '/* UnregisteredSQLString */ TRUNCATE TABLE pt_met__transactions' we caught a SQLException.
The SQL was executed with the following bind args:
()
End of verbose SQLException error message: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired
 
	at com.palantir.exception.PalantirSqlException.create(PalantirSqlException.java:76)
	at com.palantir.nexus.db.sql.BasicSQL.handleInterruptions(BasicSQL.java:514)
	at com.palantir.nexus.db.sql.BasicSQL.handleInterruptions(BasicSQL.java:494)
	at com.palantir.nexus.db.sql.BasicSQLUtils.runUninterruptably(BasicSQLUtils.java:304)
	at com.palantir.nexus.db.sql.BasicSQL.execute(BasicSQL.java:547)
	at com.palantir.nexus.db.sql.SqlConnectionHelper.executeUnregisteredQuery(SqlConnectionHelper.java:52)
	at com.palantir.nexus.db.sql.ConnectionBackedSqlConnectionImpl.executeUnregisteredQuery(ConnectionBackedSqlConnectionImpl.java:74)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.common.proxy.PerformanceLoggingProxy.handleInvocation(PerformanceLoggingProxy.java:100)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy5.executeUnregisteredQuery(Unknown Source)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.oracle.OracleDdlTable.truncate(OracleDdlTable.java:185)
	... 142 more
Caused by: com.palantir.util.sql.VerboseSQLException: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired
 
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.nexus.db.pool.InterceptorStatement.handleInvocation(InterceptorStatement.java:52)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy6.execute(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.nexus.db.sql.BasicSQL$BlobCleanupPreparedStatement.invoke(BasicSQL.java:344)
	at com.sun.proxy.$Proxy7.execute(Unknown Source)
	at com.palantir.sql.PreparedStatements.execute(PreparedStatements.java:41)
	at com.palantir.nexus.db.sql.BasicSQL$4$1.visit(BasicSQL.java:553)
	at com.palantir.nexus.db.sql.BasicSQL$4$1.visit(BasicSQL.java:550)
	at com.palantir.nexus.db.sql.BasicSQL.wrapPreparedStatement(BasicSQL.java:482)
	at com.palantir.nexus.db.sql.BasicSQL.access$100(BasicSQL.java:72)
	at com.palantir.nexus.db.sql.BasicSQL$4.call(BasicSQL.java:550)
	at com.palantir.nexus.db.sql.BasicSQL$4.call(BasicSQL.java:547)
	at com.palantir.nexus.db.sql.BasicSQLUtils$1.call(BasicSQLUtils.java:284)
	at com.palantir.nexus.db.ThreadConfinedProxy$1.call(ThreadConfinedProxy.java:102)
	at com.palantir.common.concurrent.ThreadNamingCallable.call(ThreadNamingCallable.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 73 more
```

**Comment by rhero** [comment]
@clockfort how often is this happening, and we've only seen this on internal testing, correct? Just want to get a sense of impact and make sure that actual customers aren't hitting this.

**Comment by clockfort** [comment]
Only seen in internal testing;
no real reason you couldn't see it at a customer, just a matter of most customers:
- wouldn't be running truncate often
- most workflows hopefully do not involve truncating something you're still actively touching

**Comment by hsaraogi** [comment]
We are probably not going to fix this as this only happened on the Transaction table and we are not aware of applications truncating tables explicitly.
