### ISSUE TITLE
Perf CLI crashes on KVS-agnostic benchmarks

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1634]
Internal benchmarking was brought down because of #1613. Specifically, our tooling around JMH makes the assumption that all benchmarks are parameterised by KVS, and this appears detected simply by using the KVS (or not - adding an unused table parameter to the HttpBenchmarks resolved the issue). JMH is smart enough not to parameterise the HttpBenchmark on KVS, only running it once instead of once per KVS, but our assumption that every test must have a DB URI parameter fails here.

```java
    stderr: Exception in thread "main" java.lang.NullPointerException
	at com.palantir.atlasdb.performance.backend.DockerizedDatabaseUri.fromUriString(DockerizedDatabaseUri.java:33)
	at com.palantir.atlasdb.performance.PerformanceResults.lambda$writeToFile$25(PerformanceResults.java:58)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.palantir.atlasdb.performance.PerformanceResults.writeToFile(PerformanceResults.java:72)
	at com.palantir.atlasdb.performance.cli.AtlasDbPerfCli.runJmh(AtlasDbPerfCli.java:141)
	at com.palantir.atlasdb.performance.cli.AtlasDbPerfCli.run(AtlasDbPerfCli.java:104)
	at com.palantir.atlasdb.performance.cli.AtlasDbPerfCli.main(AtlasDbPerfCli.java:96)
```

This prevents internal benchmarking from reporting any results.

**Comment by jeremyk-91** [comment]
Fixed in #1635. Note #1641 is something we should get to, but at least the build is back up and we're out of P1-land.
