### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by jugaadi** [palantir/atlasdb#1807]
On `gradle run`, got the following error. Please guild me on how to proceed with the installation. Need to test it.

`:atlasdb-ete-tests:run
Exception in thread "main" java.io.FileNotFoundException: File var/conf/atlasdb-ete.yml not found
        at io.dropwizard.configuration.FileConfigurationSourceProvider.open(FileConfigurationSourceProvider.java:14)
        at io.dropwizard.configuration.SubstitutingSourceProvider.open(SubstitutingSourceProvider.java:37)
        at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:86)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at com.palantir.atlasdb.AtlasDbEteServer.main(AtlasDbEteServer.java:55)
`

BTW do you have a mailing list or google group or chat portal?

**Comment by jboreiko** [comment]
Hey @jugaadi!

Thanks for reaching out.  We don't currently have a public mailing list / chat / group.  That said we hope to be responsive to queries received through github.

Run might not do what you believe it to do.  AtlasDB itself is a *library* not a standalone database.  So kicking off a run task in gradle will start up several of our runnables which will lack their appropriate configuration paths.  I've printed the help message below to help provide additional detail:

```
✔ jboreiko@jboreiko-mbp:~/git/work/atlasdb [develop|⚑ 7] 14:08$ gw help --task run
Configuration on demand is an incubating feature.
:help
Detailed task information for run

Paths
     :atlasdb-cli-distribution:run
     :atlasdb-console-distribution:run
     :atlasdb-ete-tests:run
     :atlasdb-perf:run
     :atlasdb-service-server:run
     :timelock-server:run
...
```
In this case it appears you are failing to start an End-To-End testing server we deploy to docker nodes for some of ETE tests.  This task is the one listed under `:atlasdb-ete-tests:run`.  If you would like to investigate a simple application running on top of AtlasDB please check out [AtlasDbEteServer](https://github.com/palantir/atlasdb/blob/develop/atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java).  It can be run if provided with the correct configuration pointing to a functional backing store (examples of these can be found here [docker/conf](https://github.com/palantir/atlasdb/tree/develop/atlasdb-ete-tests/docker/conf)

**Comment by jboreiko** [comment]
I'm going to close this ticket for the time being as this behavior is expected.  That said, we would be happy to help get you up and running!  Cheers.
