### ISSUE TITLE
H2 on DbKvs doesn't work

### ISSUE THREAD

**Issue by tjwilson90** [palantir/atlasdb#2056]
Recent emails have indicated that rocksdb is disappearing as an atlas backend. I am fine with this. I do however still have the need for an atlas backend that's easy to run for local development.

Recent emails have also indicated that this is intended to be H2 backed DbKvs. I am fine with this too, except that it does not appear to work.

- There is zero testing in atlas for H2 on DbKvs. Amusingly, there is more testing for H2 on JdbcKvs.
- The current code appears to simply treat H2 exactly like postgres. H2 does not work exactly like postgres. On startup I immediately get the error
```
End of verbose SQLException error message: Column "ID" not found; SQL statement:
/* UnregisteredSQLString */ INSERT INTO dual (id) SELECT 1 WHERE NOT EXISTS ( SELECT id FROM dual WHERE id = 1 ) [42122-196]
	at com.palantir.exception.PalantirSqlException.create(PalantirSqlException.java:76)
	at com.palantir.nexus.db.sql.BasicSQL.handleInterruptions(BasicSQL.java:523)
	at com.palantir.nexus.db.sql.BasicSQL.handleInterruptions(BasicSQL.java:503)
	at com.palantir.nexus.db.sql.BasicSQLUtils.runUninterruptably(BasicSQLUtils.java:304)
	at com.palantir.nexus.db.sql.BasicSQL.execute(BasicSQL.java:556)
	at com.palantir.nexus.db.sql.SqlConnectionHelper.executeUnregisteredQuery(SqlConnectionHelper.java:54)
	at com.palantir.nexus.db.sql.ConnectionBackedSqlConnectionImpl.executeUnregisteredQuery(ConnectionBackedSqlConnectionImpl.java:74)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.postgres.PostgresTableInitializer.createUtilityTables(PostgresTableInitializer.java:42)
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs$2.apply(DbKvs.java:245)
...
```
- The H2 ddl configuration requires me to set the name of the metadata table. I would prefer to just have a default like the postgres and oracle ddl configuration.
- The current H2 configuration on DbKvs appears to be setting up a purely in-memory database. I am fine with this as an option, but really need a persistent db like rocks, or H2 on JdbcKvs. If I'm going to use an in-memory database, I'd probably just use the built-in in memory kvs.

**Comment by gmaretic** [comment]
Confirmed that there are multiple hurdles to overcome to make H2 backed DbKvs work. Decided to keep JdbcKvs, but restrict it to be backable by H2 only as a local dev environment solution.

**Comment by hsaraogi** [comment]
We need to check that H2 supports atomic CAS operations and proceed from there.
