### ISSUE TITLE
Cassandra error when you delete all columns in a row in table with dynamic columns

### ISSUE THREAD

**Issue by sh4nth** [palantir/atlasdb#216]
If you add a row to a table with dynamic columns and then delete all the columns in it before commiting, then a future get on the row throws the following NPE:

```
ERROR [2016-02-09 23:56:23,230] com.palantir.remoting.http.server.JsonExceptionMapper: null
! org.apache.cassandra.thrift.InvalidRequestException: null
! at org.apache.cassandra.thrift.Cassandra$get_range_slices_result$get_range_slices_resultStandardScheme.read(Cassandra.java:17600) ~[cassandra-thrift-2.1.7.jar:2.1.7]
! at org.apache.cassandra.thrift.Cassandra$get_range_slices_result$get_range_slices_resultStandardScheme.read(Cassandra.java:17567) ~[cassandra-thrift-2.1.7.jar:2.1.7]
! at org.apache.cassandra.thrift.Cassandra$get_range_slices_result.read(Cassandra.java:17493) ~[cassandra-thrift-2.1.7.jar:2.1.7]
! at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.9.2.jar:0.9.2]
! at org.apache.cassandra.thrift.Cassandra$Client.recv_get_range_slices(Cassandra.java:811) ~[cassandra-thrift-2.1.7.jar:2.1.7]
! at org.apache.cassandra.thrift.Cassandra$Client.get_range_slices(Cassandra.java:795) ~[cassandra-thrift-2.1.7.jar:2.1.7]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService$7$1.apply(CassandraKeyValueService.java:853) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService$7$1.apply(CassandraKeyValueService.java:826) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:117) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:97) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.common.pooling.ForwardingPoolingContainer.runWithPooledResource(ForwardingPoolingContainer.java:30) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.pooling.ForwardingPoolingContainer.runWithPooledResource(ForwardingPoolingContainer.java:30) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.RetriablePoolingContainer.runWithPooledResource(RetriablePoolingContainer.java:56) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService$7.getPage(CassandraKeyValueService.java:826) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService$7.getFirstPage(CassandraKeyValueService.java:817) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService$7.getFirstPage(CassandraKeyValueService.java:814) ~[atlasdb-cassandra-0.3.23.jar:na]
! at com.palantir.util.paging.AbstractPagingIterable$PagingIterator.computeNext(AbstractPagingIterable.java:60) ~[atlasdb-commons-0.3.23.jar:na]
! ... 105 common frames omitted
! Causing: com.palantir.common.exception.PalantirRuntimeException: null
! at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:100) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.Throwables.createPalantirRuntimeException(Throwables.java:92) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.Throwables.throwUncheckedException(Throwables.java:88) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.util.paging.AbstractPagingIterable$PagingIterator.computeNext(AbstractPagingIterable.java:62) ~[atlasdb-commons-0.3.23.jar:na]
! at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
! at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
! at com.palantir.common.base.ClosableIterators$1.hasNext(ClosableIterators.java:32) ~[atlasdb-commons-0.3.23.jar:na]
! at com.google.common.collect.Iterators$9.hasNext(Iterators.java:935) ~[guava-18.0.jar:na]
! at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:268) ~[guava-18.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction$BatchSizeIncreasingRangeIterator.getBatch(SnapshotTransaction.java:762) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction$5.computeNext(SnapshotTransaction.java:666) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction$5.computeNext(SnapshotTransaction.java:663) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
! at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
! at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547) ~[guava-18.0.jar:na]
! at com.palantir.common.base.ClosableIterators$1.hasNext(ClosableIterators.java:32) ~[atlasdb-commons-0.3.23.jar:na]
! at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43) ~[guava-18.0.jar:na]
! at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1149) ~[guava-18.0.jar:na]
! at com.palantir.common.collect.IteratorUtils$4.computeNext(IteratorUtils.java:171) ~[atlasdb-commons-0.3.23.jar:na]
! at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
! at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
! at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43) ~[guava-18.0.jar:na]
! at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650) ~[guava-18.0.jar:na]
! at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
! at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
! at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43) ~[guava-18.0.jar:na]
! at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43) ~[guava-18.0.jar:na]
! at com.google.common.collect.Iterators$6.hasNext(Iterators.java:617) ~[guava-18.0.jar:na]
! at com.palantir.common.base.BatchingVisitableFromIterable.batchAcceptSizeHint(BatchingVisitableFromIterable.java:64) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.AbstractBatchingVisitable.batchAccept(AbstractBatchingVisitable.java:39) ~[atlasdb-commons-0.3.23.jar:na]
! at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[na:na]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
! at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
! at com.palantir.common.proxy.SingleCallProxy.invoke(SingleCallProxy.java:48) ~[atlasdb-commons-0.3.23.jar:na]
! at com.sun.proxy.$Proxy73.batchAccept(Unknown Source) ~[na:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getBatchingVisitableFromIterator(SnapshotTransaction.java:602) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.access$700(SnapshotTransaction.java:136) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransaction$2.batchAcceptSizeHint(SnapshotTransaction.java:579) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.common.base.AbstractBatchingVisitable.batchAccept(AbstractBatchingVisitable.java:43) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.BatchingVisitables$12.batchAcceptSizeHint(BatchingVisitables.java:293) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.AbstractBatchingVisitable.batchAccept(AbstractBatchingVisitable.java:43) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.BatchingVisitables$17.batchAccept(BatchingVisitables.java:489) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.BatchingVisitableView.forEach(BatchingVisitableView.java:115) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.common.base.BatchingVisitableView.forEach(BatchingVisitableView.java:127) ~[atlasdb-commons-0.3.23.jar:na]
! at com.palantir.foundry.catalog.store.atlas.AtlasCatalogStore.lambda$visitAllFiles$67(AtlasCatalogStore.java:651) ~[foundry-catalog-1.0.0-beta10-dev-65-g17901ab.dirty.jar:na]
! at com.palantir.foundry.catalog.store.atlas.AtlasCatalogStore$$Lambda$30/1836991353.execute(Unknown Source) ~[na:na]
! at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:68) ~[atlasdb-client-0.3.23.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskReadOnly(SnapshotTransactionManager.java:207) ~[atlasdb-impl-shared-0.3.23.jar:na]
! at com.palantir.foundry.catalog.store.atlas.AtlasCatalogStore.visitAllFiles(AtlasCatalogStore.java:617) ~[foundry-catalog-1.0.0-beta10-dev-65-g17901ab.dirty.jar:na]```

@rjullman

**Comment by tmgordeeva** [comment]
https://github.com/palantir/atlasdb/pull/225 to fix this (also as you've noticed, higher batch sizes can work around this, but we should still fix it)
