### ISSUE TITLE
TimeLock: Async all the things

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2181]
Nathan Ziebart
[11:21] 
also, re: the thread pools getting full. TBH i think it's still possible for the pool to fill up given enough concurrent requests, since we do still block on paxos

[11:22] 
i can repro with stress tests. however, the solution is pretty simple: just bump the jetty queue size. <FRUITY> was running with defaults (1024 threads, 1024 maxQueued).

Jeremy Kong
[11:22 PM] 
Yep, indeed we do block on the leadership stuff

[11:24] 
1024 seems pretty low, under high load if there’s a second’s delay the queue + threads could easily get full

Nathan Ziebart [11:24 PM] 
i did catch one stack trace with 1k threads blocked there on internal cloud:

Nathan Ziebart [11:25 PM] 
yep, exactly. our requests rates are high enough that that's totally plausible

[11:25] 
could be interesting to make the leadership check also async

Jeremy Kong
[11:25 PM] 
Ah right. We batch the paxos calls synchronously on the client side too

Nathan Ziebart [11:28 PM] 
i bumped the maxQueuedRequests to 10,000 (leaving maxThreads at 1024) and i can run the contendedWriteTxn benchmark with 8192 threads with no errors or elections

---

As @nziebart points out, there is still scope for our queues to fill up if a leadership check _just_ takes a bit too long (because of the paxos checks which are blocking) - doing these async as well could be interesting.

Short run fix could be to bump the maxQueuedRequests limit, as noted above.

**Comment by nziebart** [comment]
Another related issue here is that http/2 seems to sometimes get into a bad state if it jetty rejects requests from the queue. 

With HTTPS, a queue rejection will result in an error like ` Remote host closed connection during handshake executing` getting propagated to `FailoverFeignTarget`. We then do some sane backoff and retry, and things eventually succeed.

With HTTP/2, there is no error propagated to `FailoverFeignTarget`. Instead, the request is silently retried, and can sometimes get into a deadlock / livelock state where a bunch of threads are blocked  on either 
```
	at okhttp3.internal.framed.FramedStream.waitForIo(FramedStream.java:584)
```
or apparently stuck filling in a stacktrace
```
  java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked <0x00000000fff491f0> (a java.io.IOException)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at okhttp3.internal.framed.FramedConnection.newStream(FramedConnection.java:238)
	- locked <0x00000000e309d620> (a okhttp3.internal.framed.FramedConnection)
	- locked <0x00000000e31672a0> (a okhttp3.internal.framed.Http2$Writer)
```
(the locks on `Http2$Writer` and `FramedConnection` then block other requests that are trying to call `newStream()`) 

Meanwhile jetty gets stuck at:
```
	at org.eclipse.jetty.server.HttpInput.blockForContent(HttpInput.java:364)
```

I'm not sure how far down the rabbit hole we want to go in these issues; it seems like making the queue size generously large and keeping an eye on things in the field might be the best way to proceed for now. If we end up moving to websockets for performance, that would also solve this issue AFAIK.
