### ISSUE TITLE
v2 tables don't work for Persisters

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2485]
The following table definition:
```
schema.addTableDefinition("schema_version", new TableDefinition() {
            {
                javaTableName("SchemaVersion");
                enableV2Table();
                allSafeForLoggingByDefault();
                rowName();
                rowComponent("name", ValueType.STRING);
                ignoreHotspottingChecks();

                columns();
                // TODO add online schema version here?
                column("info", "v", SchemaVersionInfoPersister.class);
            }
        });
```

Fails with:
```
Exception in thread "main" java.lang.IllegalArgumentException: array types cannot be represented as a ClassName
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.ClassName.get(ClassName.java:141)
        at com.palantir.atlasdb.table.description.render.TableClassRendererV2.renderNamedGetColumn(TableClassRendererV2.java:263)
        at com.palantir.atlasdb.table.description.render.TableClassRendererV2.renderNamedGet(TableClassRendererV2.java:234)
        at com.palantir.atlasdb.table.description.render.TableClassRendererV2.getMethods(TableClassRendererV2.java:192)
        at com.palantir.atlasdb.table.description.render.TableClassRendererV2.buildTypeSpec(TableClassRendererV2.java:139)
        at com.palantir.atlasdb.table.description.render.TableClassRendererV2.render(TableClassRendererV2.java:119)
        at com.palantir.atlasdb.table.description.render.TableRendererV2.render(TableRendererV2.java:38)
        at com.palantir.atlasdb.table.description.Schema.renderTables(Schema.java:326)
```

**Comment by gsheasby** [comment]
@pnepywoda for SA.
