### ISSUE TITLE
New and worrisome flaky test 

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2516]
Saw the following tests fail after the PR #2491 merged, perhaps related.

```
[00:12:03]         at com.palantir.atlasdb.timelock.PaxosTimeLockServerIntegrationTest.lockAndUnlockAndCountExceptions(PaxosTimeLockServerIntegrationTest.java:192)
[00:12:03]         at com.palantir.atlasdb.timelock.PaxosTimeLockServerIntegrationTest.throwsOnTwoClientsRequestingSameLockTooManyTimes(PaxosTimeLockServerIntegrationTest.java:182)
[00:12:03] 
[00:12:03]         Caused by:
[00:12:03]         okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
[00:12:03]             at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:153)
[00:12:03]             at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:120)
[00:12:03]             at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[00:12:03]             at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[00:12:03]             at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[00:12:03]             at com.palantir.atlasdb.http.FeignOkHttpClients$UserAgentAddingInterceptor.intercept(FeignOkHttpClients.java:130)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[00:12:03]             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[00:12:03]             at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
[00:12:03]             at okhttp3.RealCall.execute(RealCall.java:69)
[00:12:03]             at com.palantir.atlasdb.shaded.feign.okhttp.OkHttpClient.execute(OkHttpClient.java:155)
[00:12:03]             at com.palantir.atlasdb.shaded.feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
[00:12:03]             ... 13 more
```

```
[00:13:03] com.palantir.atlasdb.timelock.PaxosTimeLockServerIntegrationTest > classMethod FAILED
[00:13:03]     java.lang.RuntimeException: java.util.concurrent.TimeoutException
[00:13:03] 
[00:13:03]         Caused by:
[00:13:03]         java.util.concurrent.TimeoutException
```

**Comment by nziebart** [comment]
@hsaraogi the PR you referenced is unmerged

**Comment by hsaraogi** [comment]
Oops, so there might be some other cause here, but I saw this flake for the first time.

**Comment by hsaraogi** [comment]
If we see it again, we should look into this.

**Comment by gsheasby** [comment]
Hit this on internal build palantir://7000.
