### ISSUE TITLE
Background sweep can fail if the sweep.priority table has duplicate keys

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2544]
```
WARN  [2017-10-23 17:30:01,768] com.palantir.atlasdb.sweep.BackgroundSweeperImpl: The background sweep job failed unexpectedly with candidate batch size 512, delete batch size 500, and 500 cell+timestamp pairs to examine. Attempting to continue with a lower batch size...
! java.lang.IllegalStateException: Duplicate key SweepPriority{tableRef=default.todo, writeCount=0, lastSweepTimeMillis=1508778423348, minimumSweptTimestamp=1010022, staleValuesDeleted=208, cellTsPairsExamined=211}
! at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[na:1.8.0_92]
! at java.util.HashMap.merge(HashMap.java:1253) ~[na:1.8.0_92]
! at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[na:1.8.0_92]
! at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_92]
! at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_92]
! at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_92]
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_92]
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_92]
! at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_92]
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_92]
! at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_92]
! at com.palantir.atlasdb.sweep.priority.NextTableToSweepProviderImpl.chooseNextTableToSweep(NextTableToSweepProviderImpl.java:54) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl$1.execute(BackgroundSweeperImpl.java:199) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl$1.execute(BackgroundSweeperImpl.java:191) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks$1.execute(LockAwareTransactionTasks.java:32) ~[atlasdb-lock-api/:na]
! at com.palantir.atlasdb.transaction.api.LockAwareTransactionTasks.lambda$asLockUnaware$0(LockAwareTransactionTasks.java:49) ~[atlasdb-lock-api/:na]
! at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskThrowOnConflict(AbstractTransactionManager.java:102) ~[atlasdb-client/:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.finishRunTaskWithLockThrowOnConflict(SnapshotTransactionManager.java:154) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.finishRunTaskWithLockThrowOnConflict(SerializableTransactionManager.java:37) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:126) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:37) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:123) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:55) ~[atlasdb-client/:na]
! at com.palantir.atlasdb.transaction.impl.AutoDelegate_SerializableTransactionManager.runTaskWithRetry(AutoDelegate_SerializableTransactionManager.java:112) ~[atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.getTableToSweep(BackgroundSweeperImpl.java:190) [atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.runOnce(BackgroundSweeperImpl.java:176) [atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.grabLocksAndRun(BackgroundSweeperImpl.java:137) [atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.checkConfigAndRunSweep(BackgroundSweeperImpl.java:125) [atlasdb-impl-shared/:na]
! at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.run(BackgroundSweeperImpl.java:113) [atlasdb-impl-shared/:na]
```

This is because we try to collect values to a map :(.

**Comment by hsaraogi** [comment]
repro can be found on the branch `feature/ex-testing`.
