### ISSUE TITLE
Deprecated TransactionManagers.create methods are broken

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2581]
Versions affected: 0.62.0, 0.62.1

Products using deprecated versions of TransactionManagers.create(...) that do not specify a user agent will fail (at runtime, seemingly), because there is no default in the Immutable object.

```
Exception in thread "main" java.lang.IllegalStateException: Cannot build TransactionManagers, some of required attributes are not set [userAgent]
    at com.palantir.atlasdb.factory.ImmutableTransactionManagers$Builder.build(ImmutableTransactionManagers.java:660)
    at com.palantir.atlasdb.factory.TransactionManagers$Builder.buildSerializable(TransactionManagers.java:153)
    at com.palantir.atlasdb.factory.TransactionManagers.create(TransactionManagers.java:233)
    at com.palantir.atlasdb.factory.TransactionManagers.create(TransactionManagers.java:211)
```

**Comment by tpetracca** [comment]
#2542 broke https://github.com/palantir/atlasdb/blob/develop/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L219
