### ISSUE TITLE
could not serialize HeldLocksToken

### ISSUE THREAD

**Issue by bavardage** [palantir/atlasdb#264]
No json stuffs for HeldLocksToken, so blows up when passed via ForwardingLocksService

![image](https://cloud.githubusercontent.com/assets/24711/13930532/8782af72-ef75-11e5-9b9a-3ba7dcbff97c.png)

**Comment by jared2501** [comment]
Hey @rjullman looks like this fixed the stacktrace, but another one has showed up:

```
stemma1.palantir.dev             | WARN  [2016-03-28 23:24:07,234] /stemma: Internal error during receive-pack to 1c588d6e-4990-4357-b79e-0be123b5241a
stemma1.palantir.dev             | ! com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "anonymous" (class com.palantir.lock.LockClient), not marked as ignorable (one known property: "clientId"])
stemma1.palantir.dev             | !  at [Source: java.io.BufferedReader@65fd2eeb; line: 1, column: 73] (through reference chain: com.palantir.lock.LockClient["anonymous"])
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:228) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:402) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer._deserializeUsingPropertyBased(BuilderBasedDeserializer.java:339) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:281) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:147) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2787) ~[jackson-databind-2.6.3.jar:2.6.3]
stemma1.palantir.dev             | ! at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at com.palantir.atlasdb.http.TextDelegateDecoder.decode(TextDelegateDecoder.java:70) ~[atlasdb-config-0.3.33.jar:na]
stemma1.palantir.dev             | ! at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:146) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:118) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! ... 75 common frames omitted
stemma1.palantir.dev             | ! Causing: feign.FeignException: Unrecognized field "anonymous" (class com.palantir.lock.LockClient), not marked as ignorable (one known property: "clientId"])
stemma1.palantir.dev             | !  at [Source: java.io.BufferedReader@65fd2eeb; line: 1, column: 73] (through reference chain: com.palantir.lock.LockClient["anonymous"]) reading POST https://stemma1.palantir.dev:7333/stemma/api/lock/try-lock/
stemma1.palantir.dev             | ! at feign.FeignException.errorReading(FeignException.java:48) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:127) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94) ~[feign-core-8.11.0.jar:8.11.0]
stemma1.palantir.dev             | ! at com.sun.proxy.$Proxy52.lockAndGetHeldLocks(Unknown Source) ~[na:na]
stemma1.palantir.dev             | ! at com.palantir.lock.ForwardingRemoteLockService.lockAndGetHeldLocks(ForwardingRemoteLockService.java:36) ~[lock-api-0.3.33.jar:na]
stemma1.palantir.dev             | ! at com.palantir.lock.client.LockRefreshingRemoteLockService.lockAndGetHeldLocks(LockRefreshingRemoteLockService.java:91) ~[lock-api-0.3.33.jar:na]
stemma1.palantir.dev             | ! at com.palantir.stemma.repository.locks.DefaultAtlasRepositoryLockProvider.acquireRefWriteLock(DefaultAtlasRepositoryLockProvider.java:85) ~[stemma-server-0.5.1-dev-57-gb376009.jar:na]
stemma1.palantir.dev             | ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
stemma1.palantir.dev             | ! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
stemma1.palantir.dev             | ! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
stemma1.palantir.dev             | ! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
stemma1.palantir.dev             | ! at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:111) ~[tritium-lib-0.1.2.jar:0.1.2]
stemma1.palantir.dev             | ! at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:88) ~[tritium-lib-0.1.2.jar:0.1.2]
stemma1.palantir.dev             | ! at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:69) ~[tritium-lib-0.1.2.jar:0.1.2]
stemma1.palantir.dev             | ! at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-19.0.jar:na]
stemma1.palantir.dev             | ! at com.sun.proxy.$Proxy67.acquireRefWriteLock(Unknown Source) ~[na:na]
stemma1.palantir.dev             | ! at com.palantir.stemma.repository.store.AtlasLockingSingleRepositoryStore.acquireLockIfNotAcquiredAlready(AtlasLockingSingleRepositoryStore.java:113) ~[stemma-server-0.5.1-dev-57-gb376009.jar:na]
stemma1.palantir.dev             | ! at com.palantir.stemma.repository.store.AtlasLockingSingleRepositoryStore.getRefs(AtlasLockingSingleRepositoryStore.java:61) ~[stemma-server-0.5.1-dev-57-gb376009.jar:na]
stemma1.palantir.dev             | ! at com.palantir.stemma.repository.store.AtlasRefDatabase.scanAllRefs(AtlasRefDatabase.java:42) ~[stemma-server-0.5.1-dev-57-gb376009.jar:na]
stemma1.palantir.dev             | ! at org.eclipse.jgit.internal.storage.dfs.DfsRefDatabase.read(DfsRefDatabase.java:301) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.internal.storage.dfs.DfsRefDatabase.getRefs(DfsRefDatabase.java:120) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.lib.Repository.getAllRefs(Repository.java:1018) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.transport.BaseReceivePack.setAdvertisedRefs(BaseReceivePack.java:423) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.transport.BaseReceivePack.getAdvertisedOrDefaultRefs(BaseReceivePack.java:967) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:182) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:161) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.ReceivePackServlet.doPost(ReceivePackServlet.java:193) ~[org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
stemma1.palantir.dev             | ! at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:237) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.ReceivePackServlet$Factory.doFilter(ReceivePackServlet.java:150) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:151) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:80) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:215) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:101) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:175) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:133) [org.eclipse.jgit.http.server-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
stemma1.palantir.dev             | ! at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
stemma1.palantir.dev             | ! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dropwizard-jetty-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132) [dropwizard-jetty-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [dropwizard-servlets-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [dropwizard-jersey-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [dropwizard-jersey-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at com.palantir.stemma.servlet.ChallengeForHttpAuthFilter.doFilter(ChallengeForHttpAuthFilter.java:67) [stemma-server-0.5.1-dev-57-gb376009.jar:na]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at com.palantir.websecurity.filters.JerseyAwareWebSecurityFilter.doFilter(JerseyAwareWebSecurityFilter.java:63) [dropwizard-web-security-0.12.0.jar:na]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [metrics-jetty9-3.1.2.jar:3.1.2]
stemma1.palantir.dev             | ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.9.1.jar:0.9.1]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.13.v20150730.jar:9.2.13.v20150730]
stemma1.palantir.dev             | ! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
multipass.palantir.dev           | WARN  [2016-03-28 23:24:07,297] com.palantir.multipass.token.codec.DefaultJwtDecoder: Received JWT token that is not a Session Token.
```

**Comment by rjullman** [comment]
https://github.com/palantir/atlasdb/pull/289
