### ISSUE TITLE
clean-cass-locks-state throws "Multiple schema mutation lock tables have been created"

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2852]
On running:
PCLOUD [palantir@xxxx service]$ ./bin/atlasdb-cli --offline -c var/conf/install.yml clean-cass-locks-state

We got:

```
19:36:14.149 [main calling cassandra host keppel-soa-cassandra-16.ops.palantir.local/10.3.41.149:9160 started at 2018-01-11T19:36:14.147Z - 5] DEBUG c.p.a.k.c.CassandraClientPoolingContainer - During com.palantir.atlasdb.keyvalue.cassandra.qos.QosCassandraClient@640f11a1 check-in, cleaned up a read buffer of 1277 bytes of host keppel-soa-cassandra-16.ops.palantir.local
19:36:14.153 [main] ERROR com.palantir.atlasdb.cli.AtlasCli - Fatal exception thrown during cli command execution.  Exiting.
java.lang.IllegalStateException: Multiple schema mutation lock tables have been created.
This happens when multiple nodes have themselves as lockLeader in the configuration.
Please ensure the lockLeader is the same for each node, stop all Atlas clients using this keyspace, restart your cassandra cluster and run the clean-cass-locks-state cli command.
The tables that clashed were: [_locks_5fe819e3_7ff0_4884_b3a7_b7f96091bc58, _locks_c146b83a_27ae_40b4_9498_2fe69959dbb8]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.getSingleTable(UniqueSchemaMutationLockTable.java:87) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.ensureLockTableExists(UniqueSchemaMutationLockTable.java:80) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.getOnlyTable(UniqueSchemaMutationLockTable.java:48) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.tryInitialize(CassandraKeyValueServiceImpl.java:320) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$000(CassandraKeyValueServiceImpl.java:155) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$InitializingWrapper.tryInitialize(CassandraKeyValueServiceImpl.java:166) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.async.initializer.AsyncInitializer.tryInitializeInternal(AsyncInitializer.java:141) ~[atlasdb-commons-0.72.0.jar:0.72.0]
        at com.palantir.async.initializer.AsyncInitializer.initialize(AsyncInitializer.java:64) ~[atlasdb-commons-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:266) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:235) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:227) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.command.CleanCassLocksStateCommand.call(CleanCassLocksStateCommand.java:43) ~[atlasdb-cli-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.command.CleanCassLocksStateCommand.call(CleanCassLocksStateCommand.java:32) ~[atlasdb-cli-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.AtlasCli.main(AtlasCli.java:65) ~[atlasdb-cli-0.72.0.jar:0.72.0]```

**Comment by gsheasby** [comment]
This is because the CLI uses the `CassandraKeyValueServcieImpl` object, which uses `UniqueSchemaMutationLockTables`, which enforces the very constraint we're trying to meet 🤦‍♂️ 🤦‍♀️ 

The fix will be to remove `cleanUpSchemaMutationLockTablesState` from the `CassandraKeyValueService` interface, which will require a non-trivial refactor and extracting several objects from `CassandraKeyValueService`. I've sketched out work for this, which may stretch to multiple PRs.
