### ISSUE TITLE
Sweep can try to delete cells with null startTs 

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2881]
```
com.palantir.common.exception.AtlasDbDependencyException: {throwable0_message}
	at com.palantir.common.base.Throwables.createAtlasDbDependencyException(Throwables.java:100)
	at com.palantir.common.base.Throwables.unwrapAndThrowAtlasDbDependencyException(Throwables.java:92)
	at com.palantir.atlasdb.qos.ratelimit.QosAwareThrowables.unwrapAndThrowRateLimitExceededOrAtlasDbDependencyException(QosAwareThrowables.java:42)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.deleteOnSingleHost(CassandraKeyValueServiceImpl.java:1403)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.delete(CassandraKeyValueServiceImpl.java:1338)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$delete$33(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.lambda$maybeLog$18(KvsProfilingLogger.java:96)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:119)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:102)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:398)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.delete(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.delete(ForwardingKeyValueService.java:70)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.delete(TracingKeyValueService.java:147)
	at sun.reflect.GeneratedMethodAccessor544.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:140)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:117)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:97)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
	at com.sun.proxy.$Proxy51.delete(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.delete(ValidatingQueryRewritingKeyValueService.java:121)
	at com.palantir.atlasdb.sweep.CellsSweeper.sweepCells(CellsSweeper.java:96)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.sweepBatch(SweepTaskRunner.java:263)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.doRun(SweepTaskRunner.java:192)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.runInternal(SweepTaskRunner.java:140)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.run(SweepTaskRunner.java:105)
	at com.palantir.atlasdb.sweep.SpecificTableSweeper.runOneIteration(SpecificTableSweeper.java:131)
	at com.palantir.atlasdb.sweep.SpecificTableSweeper.runOnceAndSaveResults(SpecificTableSweeper.java:125)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.runOnce(BackgroundSweeperImpl.java:215)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.grabLocksAndRun(BackgroundSweeperImpl.java:187)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.checkConfigAndRunSweep(BackgroundSweeperImpl.java:176)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.run(BackgroundSweeperImpl.java:129)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: {throwable1_message}
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:220)
	at com.google.common.collect.ImmutableList.sortedCopyOf(ImmutableList.java:338)
	at com.google.common.collect.Ordering.immutableSortedCopy(Ordering.java:876)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$8.apply(CassandraKeyValueServiceImpl.java:1357)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$8.apply(CassandraKeyValueServiceImpl.java:1346)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:128)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:104)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:652)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:604)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.deleteOnSingleHost(CassandraKeyValueServiceImpl.java:1346)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.delete(CassandraKeyValueServiceImpl.java:1338)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$delete$33(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.lambda$maybeLog$18(KvsProfilingLogger.java:96)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:119)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:102)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:398)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.delete(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.delete(ForwardingKeyValueService.java:70)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.delete(TracingKeyValueService.java:147)
	at sun.reflect.GeneratedMethodAccessor544.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:140)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:117)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:97)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
	at com.sun.proxy.$Proxy51.delete(Unknown Source)
	at com.palantir.atlasdb.keyvalue.impl.ValidatingQueryRewritingKeyValueService.delete(ValidatingQueryRewritingKeyValueService.java:121)
	at com.palantir.atlasdb.sweep.CellsSweeper.sweepCells(CellsSweeper.java:96)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.sweepBatch(SweepTaskRunner.java:263)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.doRun(SweepTaskRunner.java:192)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.runInternal(SweepTaskRunner.java:140)
	at com.palantir.atlasdb.sweep.SweepTaskRunner.run(SweepTaskRunner.java:105)
	at com.palantir.atlasdb.sweep.SpecificTableSweeper.runOneIteration(SpecificTableSweeper.java:131)
	at com.palantir.atlasdb.sweep.SpecificTableSweeper.runOnceAndSaveResults(SpecificTableSweeper.java:125)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.runOnce(BackgroundSweeperImpl.java:215)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.grabLocksAndRun(BackgroundSweeperImpl.java:187)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.checkConfigAndRunSweep(BackgroundSweeperImpl.java:176)
	at com.palantir.atlasdb.sweep.BackgroundSweeperImpl.run(BackgroundSweeperImpl.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

PDS-62325 for SA.

**Comment by hsaraogi** [comment]
This happens when sweeping the sweep_progress_2 table.

**Comment by hsaraogi** [comment]
Mark `sweep_progress_2` hidden.
