### ISSUE TITLE
Sweep can get stuck trying to sweep _sweep_progress2

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2915]
With PR #2718, released in AtlasDB 0.71.0, we removed the `_sweep_progress2` table from the list of hidden tables. Sweep table prioritization logic is so that:

1. Sweep scans all tables in the given Cassandra keyspace.
2. Sweep filters out the hidden tables.
3. If a table has never been swept, sweep it.

If products upgraded from pre-0.71.0 to 0.71.0+, sweep would see that `_sweep_progress2` had never been swept and attempt to sweep it. Since we always write to this table using `checkAndSet`, sweep would throw a NPE:

```
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:235)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)
	at com.google.common.collect.ImmutableList.sortedCopyOf(ImmutableList.java:338)
	at com.google.common.collect.Ordering.immutableSortedCopy(Ordering.java:876)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$8.apply(CassandraKeyValueServiceImpl.java:1363)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$8.apply(CassandraKeyValueServiceImpl.java:1351)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:128)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:104)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:411)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:370)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.deleteOnSingleHost(CassandraKeyValueServiceImpl.java:1351)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.delete(CassandraKeyValueServiceImpl.java:1343)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.lambda$delete$34(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.lambda$maybeLog$19(KvsProfilingLogger.java:96)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:119)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:102)
	at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:404)
	at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.delete(ProfilingKeyValueService.java:156)
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.delete(ForwardingKeyValueService.java:70)
	at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.delete(TracingKeyValueService.java:147)
```

**Comment by fsamuel-bs** [comment]
Fixed with #2905, released on AtlasDB 0.74.0
