### ISSUE TITLE
Newer versions of AtlasDB require timestamp to be available upon startup

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#3079]
We're upgrading our service from atlas  `0.74.0`  to `0.79.1`, and there seems to have been a change that causes atlas to try to connect to the timelock server right at startup instead of on the first transaction.  This causes a startup dependency ordering, which among other things, will break our ETE tests which skip bringing up timelock altogether. 

```
Exception in thread "main" com.palantir.common.exception.AtlasDbDependencyException: Could not contact the Timelock Server.
	at com.palantir.atlasdb.factory.startup.TimeLockMigrator.tryInitialize(TimeLockMigrator.java:93)
	at com.palantir.async.initializer.AsyncInitializer.tryInitializeInternal(AsyncInitializer.java:147)
	at com.palantir.async.initializer.AsyncInitializer.initialize(AsyncInitializer.java:59)
	at com.palantir.atlasdb.factory.startup.TimeLockMigrator.migrate(TimeLockMigrator.java:77)
	at com.palantir.atlasdb.factory.TransactionManagers.createRawServicesFromTimeLock(TransactionManagers.java:641)
	at com.palantir.atlasdb.factory.TransactionManagers.createRawInstrumentedServices(TransactionManagers.java:609)
	at com.palantir.atlasdb.factory.TransactionManagers.createLockAndTimestampServices(TransactionManagers.java:563)
	at com.palantir.atlasdb.factory.TransactionManagers.serializableInternal(TransactionManagers.java:277)
	at com.palantir.atlasdb.factory.TransactionManagers.serializable(TransactionManagers.java:232)
	at com.palantir.atlasdb.factory.ImmutableTransactionManagers.access$2101(ImmutableTransactionManagers.java:42)
	at com.palantir.atlasdb.factory.ImmutableTransactionManagers$InitShim.serializable(ImmutableTransactionManagers.java:213)
	at com.palantir.atlasdb.factory.ImmutableTransactionManagers.<init>(ImmutableTransactionManagers.java:81)
```

**Comment by jeremyk-91** [comment]
Right. Would it be possible to change the configuration on the ETE tests to not use timelock / is your Atlas config in your ETE tests set up to use timelock? 

As far as I know Atlas has actually had this behaviour for quite some time where it tries to immediately connect to timelock on startup, if you're configured to use timelock. Between those versions, there was a change where we modified the handling of a case where you have (install config = embedded) + (runtime config = timelock) - out of interest are you using that specific kind of configuration?

**Comment by leeavital** [comment]
I think that is the case we're running into. We have an embedded install config (`keyValueService: { type: memory }`) and a block under timelockRuntime. 

I got rid of the `timelockRuntime` block and our ETE tests returned! Thanks
