### ISSUE TITLE
Oracle KVS attempts to use closed resources when retrying startup

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#3270]
In Oracle-flavoured DbKvs, If something goes wrong during `TransactionManagers.create`, the Hikari connection manager is closed. However, the `ConnectionManagerAwareDbKvs` object does not appear to be recycled, and the connection manager is only constructed during the creation of said object.

This means that if startup is attempted again, the same `ConnectionManagerAwareDbKvs` object is reused when attempting timestamp service creation, causing these errors:

```
ete1_1     | ERROR [2018-05-23 12:17:51,422] com.palantir.leader.proxy.AwaitingLeadershipProxy: problem creating delegate
ete1_1     | ! java.lang.Throwable: Hikari pool closed here
ete1_1     | ! at com.palantir.nexus.db.pool.HikariCPConnectionManager.close(HikariCPConnectionManager.java:248) ~[atlasdb-dbkvs-hikari
-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.nexus.db.pool.BaseConnectionManager.closeUnchecked(BaseConnectionManager.java:36) ~[commons-db-0.86.0.ja
r:0.86.0]
ete1_1     | ! at com.palantir.nexus.db.pool.ReentrantManagedConnectionSupplier.close(ReentrantManagedConnectionSupplier.java:56) ~[com
mons-db-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.impl.ConnectionManagerAwareDbKvs$2.close(ConnectionManagerAwareDbKvs.java:89) ~[a
tlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs.close(DbKvs.java:277) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.close(ForwardingKeyValueService.java:55) ~[atlasdb-clien
t-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.logging.KvsProfilingLogger.lambda$maybeLog$18(KvsProfilingLogger.java:96) ~[atlasdb-client-0.86.
0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:125) ~[atlasdb-client-0.86.0.jar:0.8
6.0]
ete1_1     | ! at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:102) ~[atlasdb-client-0.86.0.jar:0.8
6.0]
ete1_1     | ! at com.palantir.atlasdb.logging.KvsProfilingLogger.maybeLog(KvsProfilingLogger.java:95) ~[atlasdb-client-0.86.0.jar:0.86
.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.maybeLog(ProfilingKeyValueService.java:450) ~[atlasdb-cli
ent-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.ProfilingKeyValueService.close(ProfilingKeyValueService.java:355) ~[atlasdb-client
-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.SweepStatsKeyValueService.close(SweepStatsKeyValueService.java:191) ~[atlasdb-clie
nt-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.TracingKeyValueService.close(TracingKeyValueService.java:98) ~[atlasdb-client-0.86
.0.jar:0.86.0]
ete1_1     | ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
ete1_1     | ! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
ete1_1     | ! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
ete1_1     | ! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
ete1_1     | ! at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:140) ~[tritium-lib-0.9.0.jar:0.9.0]
ete1_1     | ! at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:117) ~[tritium-lib-0.9.0.jar:0.9.0]
ete1_1     | ! at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:97) ~[tritium-lib-0.9.0.jar:0.9.0]
ete1_1     | ! at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86) ~[guava-23.6-jre.jar:na]
ete1_1     | ! at com.sun.proxy.$Proxy76.close(Unknown Source) ~[na:na]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.close(ForwardingKeyValueService.java:55) ~[atlasdb-client-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.TransactionManagers.lambda$serializable$21(TransactionManagers.java:250) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_171]
ete1_1     | ! at com.palantir.atlasdb.factory.TransactionManagers.serializable(TransactionManagers.java:248) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ImmutableTransactionManagers.access$2101(ImmutableTransactionManagers.java:42) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ImmutableTransactionManagers$InitShim.serializable(ImmutableTransactionManagers.java:213) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ImmutableTransactionManagers.<init>(ImmutableTransactionManagers.java:81) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ImmutableTransactionManagers.<init>(ImmutableTransactionManagers.java:42) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ImmutableTransactionManagers$Builder.build(ImmutableTransactionManagers.java:880) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.createTransactionManager(AtlasDbEteServer.java:154) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.createTransactionManagerWithRetry(AtlasDbEteServer.java:134) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.tryToCreateTransactionManager(AtlasDbEteServer.java:107) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.run(AtlasDbEteServer.java:90) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.run(AtlasDbEteServer.java:67) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40) ~[dropwizard-core-0.9.3.jar:0.9.3]
ete1_1     | ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) ~[dropwizard-core-0.9.3.jar:0.9.3]
ete1_1     | ! at io.dropwizard.cli.Cli.run(Cli.java:70) ~[dropwizard-core-0.9.3.jar:0.9.3]
ete1_1     | ! at io.dropwizard.Application.run(Application.java:80) ~[dropwizard-core-0.9.3.jar:0.9.3]
ete1_1     | ! at com.palantir.atlasdb.AtlasDbEteServer.main(AtlasDbEteServer.java:77) ~[atlasdb-ete-tests-0.86.0.jar:0.86.0]
ete1_1     | ! Causing: java.sql.SQLException: Hikari connection pool already closed!
ete1_1     | ! at com.palantir.nexus.db.pool.HikariCPConnectionManager.checkAndGetDataSourcePool(HikariCPConnectionManager.java:180) ~[atlasdb-dbkvs-hikari-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.nexus.db.pool.HikariCPConnectionManager.acquirePooledConnection(HikariCPConnectionManager.java:103) ~[atlasdb-dbkvs-hikari-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.nexus.db.pool.HikariCPConnectionManager.getConnection(HikariCPConnectionManager.java:89) ~[atlasdb-dbkvs-hikari-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore.init(InDbTimestampBoundStore.java:91) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! ... 19 common frames omitted
ete1_1     | ! Causing: com.palantir.exception.PalantirSqlException: Hikari connection pool already closed!
ete1_1     | ! at com.palantir.exception.PalantirSqlException.create(PalantirSqlException.java:76) ~[atlasdb-commons-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore.init(InDbTimestampBoundStore.java:94) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore.create(InDbTimestampBoundStore.java:79) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.DbAtlasDbFactory.lambda$createTimestampBoundStore$1(DbAtlasDbFactory.java:102) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_171]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.DbAtlasDbFactory.createTimestampBoundStore(DbAtlasDbFactory.java:102) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.keyvalue.dbkvs.DbAtlasDbFactory.createTimestampService(DbAtlasDbFactory.java:91) ~[atlasdb-dbkvs-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ServiceDiscoveringAtlasSupplier.lambda$new$15(ServiceDiscoveringAtlasSupplier.java:121) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.atlasdb.factory.ServiceDiscoveringAtlasSupplier.getTimestampService(ServiceDiscoveringAtlasSupplier.java:139) ~[atlasdb-config-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.leader.proxy.AwaitingLeadershipProxy.onGainedLeadership(AwaitingLeadershipProxy.java:127) [leader-election-impl-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.leader.proxy.AwaitingLeadershipProxy.gainLeadershipBlocking(AwaitingLeadershipProxy.java:114) [leader-election-impl-0.86.0.jar:0.86.0]
ete1_1     | ! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
ete1_1     | ! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
ete1_1     | ! at com.palantir.common.concurrent.PTExecutors.lambda$wrapRunnable$0(PTExecutors.java:500) ~[commons-executors-0.86.0.jar:0.86.0]
ete1_1     | ! at com.palantir.remoting3.tracing.Tracers$TracingAwareRunnable.lambda$run$0(Tracers.java:202) ~[tracing-3.14.0.jar:3.14.0]
ete1_1     | ! at com.palantir.remoting3.tracing.DeferredTracer.withTrace(DeferredTracer.java:43) ~[tracing-3.14.0.jar:3.14.0]
ete1_1     | ! at com.palantir.remoting3.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:201) ~[tracing-3.14.0.jar:3.14.0]
ete1_1     | ! at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:60) ~[commons-executors-0.86.0.jar:0.86.0]
ete1_1     | ! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
ete1_1     | ! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
ete1_1     | ! at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

**Comment by gsheasby** [comment]
Things I considered for fixing this:
1. Don't start trying to gain leadership until KVS is created --> impossible* because KVS creation code uses lock/timestamp services
2. Close the AwaitingLeadershipProxy objects/threads when TM creation fails --> awkward because the proxy would need to be closable, meaning that the TimestampService would need to be closeable, even though those services themselves are never closed.
3. Add the proxy object itself to the list of closeables --> requires some funky logic, because the proxy object is not visible from outside newProxyInstance, and this code does not know about the list of Closeables.

* - you'd need a refactor to add to the state machine for leadership, with a state that's NOT_READY_TO_LEAD, from which the proxy does not attempt leadership election. You'd then need a way to transition from this state to NOT_LEADING (which generates an election) once TM creation is done.

Thing I tried but didn't get to work in a reasonable time:
1. Throw a special exception when we find the connection manager to be closed. Catch this exception in AwaitingLeadershipProxy, and exit the infinite loop. This stopped the infinite throwing of exceptions, but still didn't lead to successful leadership elections.

The failure of the last thing was possibly due to a bug, but given the time already spent on this, the uncertain time-to-fix, and the low importance (the issue has never been observed outside tests, and the test suite was fixed in another way), I'm not planning to continue working on it.

For the person in the future that wants to deal with this, the branch is [here](https://github.com/palantir/atlasdb/tree/gsheasby/fix-dbkvs-resource-reuse).
