### ISSUE TITLE
Threads getting stuck in Cassandra KVS / Thrift during shutdown

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#3329]
See PDS-69454 and PDS-69975 - @gsheasby flagged these tickets on #3317 but unfortunately after identifying the root cause in #3328 it's clear that the root cause is different since in those cases it is a bug in how we set up the TM in Dagger.

**Comment by gsheasby** [comment]
69975 seems to be an issue with TargetedSweepMetrics / puncher store (possibly a race condition?)

> As mentioned, we worked around the real issue by having Witchcraft force shutdown prior to the Apollo timeout. There's likely still an Atlas issue related to:

```
	at com.palantir.atlasdb.cleaner.KeyValueServicePuncherStore.getMillisForTimestamp(KeyValueServicePuncherStore.java:151)
	at com.palantir.atlasdb.sweep.metrics.TargetedSweepMetrics.lambda$createWithClock$0(TargetedSweepMetrics.java:60)
	at com.palantir.atlasdb.sweep.metrics.TargetedSweepMetrics$$Lambda$690/500610460.apply(Unknown Source)
	at com.palantir.atlasdb.sweep.metrics.TargetedSweepMetrics$MetricsForStrategy.lambda$new$1(TargetedSweepMetrics.java:116)
	at com.palantir.atlasdb.sweep.metrics.TargetedSweepMetrics$MetricsForStrategy$$Lambda$693/146877534.apply(Unknown Source)
	at com.palantir.util.CachedComposedSupplier.recompute(CachedComposedSupplier.java:53)
	- locked <0x00000000e1ed0178> (a com.palantir.util.CachedComposedSupplier)
	at com.palantir.util.CachedComposedSupplier.get(CachedComposedSupplier.java:45)
	at com.palantir.atlasdb.sweep.metrics.TargetedSweepMetrics$MetricsForStrategy$$Lambda$695/1095830696.getValue(Unknown Source)
```

**Comment by gmaretic** [comment]
Not hitting this anymore
