### ISSUE TITLE
Schema Mutations Against Cassandra KVS Are Not HA

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#3367]
(with respect to Cassandra).

Just hit an instance of a service failing to initialize its AtlasDb client that included a schema mutation when not all nodes of a cassandra cluster were on.

To make matters worse, technically the cluster was in a perfectly up and normal state, just one of the nodes was no longer a part of the cluster because it had been decommissioned.

We should be able to start up with a single node down; ideally it would also be a single node down that actually belongs to the ring.

**Comment by sandorw** [comment]
@tpetracca is this safe if one of the nodes is down? Can we rely on schema repairs?

**Comment by tpetracca** [comment]
it's definitely safe at a quorum of nodes. schema changes in cassandra are not read/write operations they happen via gossip and follow different rules. As long as our schema rules are as strict as our write consistency we won't run into problems because it will be impossible to service writes against a bad schema.

There is no concept of repair here. On startup every node is responsible for ensuring it is in sync with all other nodes on schema before accepting requests. And clusters immediately propagate schema changes when they occur.

**Comment by aggie05engineer** [comment]
This just caused another P0. See internal tracking number PDS-71533.

**Comment by tboam** [comment]
Will add to roadmap

**Comment by tpetracca** [comment]
PDS-71702 is potentially another occurrence and has stacktrace. Posting here for ease:
```
ERROR [2018-07-23T15:18:14.911Z] com.palantir.product.ProductServer: error starting Product server (throwable0_message:
At schema version f0ff0896-7db5-3bc5-86bd-b0abdaf79dc2:
	Node: ip.1
	Node: ip.2
At schema version UNREACHABLE:
	Node: ip.3)
java.lang.IllegalStateException: {throwable0_message}
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServices.waitForSchemaVersions(CassandraKeyValueServices.java:112)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServices.waitForSchemaVersions(CassandraKeyValueServices.java:68)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.lambda$putMetadataAndMaybeAlterTables$26(CassandraKeyValueService.java:1884)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:120)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:97)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runWithPooledResourceRecordingMetrics(CassandraClientPool.java:637)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runWithRetryOnHost(CassandraClientPool.java:599)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runWithRetry(CassandraClientPool.java:576)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.putMetadataAndMaybeAlterTables(CassandraKeyValueService.java:1878)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.upgradeFromOlderInternalSchema(CassandraKeyValueService.java:279)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.init(CassandraKeyValueService.java:239)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.create(CassandraKeyValueService.java:188)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.create(CassandraKeyValueService.java:174)
	at com.palantir.atlasdb.cassandra.CassandraAtlasDbFactory.createKv(CassandraAtlasDbFactory.java:64)
	at com.palantir.atlasdb.cassandra.CassandraAtlasDbFactory.createRawKeyValueService(CassandraAtlasDbFactory.java:45)
	at com.palantir.atlasdb.factory.ServiceDiscoveringAtlasSupplier.lambda$new$23(ServiceDiscoveringAtlasSupplier.java:75)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
	at com.palantir.atlasdb.factory.ServiceDiscoveringAtlasSupplier.getKeyValueService(ServiceDiscoveringAtlasSupplier.java:81)
	at com.palantir.atlasdb.factory.TransactionManagers.create(TransactionManagers.java:224)
	at com.palantir.atlasdb.factory.TransactionManagers.create(TransactionManagers.java:203)
```

**Comment by gmaretic** [comment]
We never did allow this without all nodes agreeing on schema version. We made a change in https://github.com/palantir/atlasdb/pull/2390 to allow the case where a quorum agrees and the rest is unreachable for `system_add_column_family`.
@tpetracca, what exactly are schema changes here -- are both `system_update_column_family` and `system_drop_column_family` then fine if we have a quorum that agrees and the rest unreachable?

**Comment by tpetracca** [comment]
I don't know what the schema changes were. Generally we need any operation that is critical path (which is at least `system_add_column_family` ad `system_update_column_family`) to be HA. So if at least a quorum of nodes are alive and agree we should do the action. UNREACHABLE implies the node is unavailable.

**Comment by gmaretic** [comment]
https://github.com/palantir/atlasdb/pull/3480 changes the wait on all the schema changes. If this is safe we should just do it. If there is a reason to do only `system_add_column_family` and `system_update_column_family`, let me know.

**Comment by tpetracca** [comment]
Don't think there's a reason to restrict to just those. I just care most about them because as far as I know they're on critical path for regular operation atlas codepaths.
