### ISSUE TITLE
Figure out why sweep benchmarks are failing

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#3383]
```
java.lang.AssertionError: 
Expected: is <9L>
     but: was <16L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.palantir.atlasdb.performance.benchmarks.SweepBenchmarks.runMultiSweep(SweepBenchmarks.java:64)
	at com.palantir.atlasdb.performance.benchmarks.SweepBenchmarks.multipleUniformSweepRun(SweepBenchmarks.java:98)
	at com.palantir.atlasdb.performance.benchmarks.generated.SweepBenchmarks_multipleUniformSweepRun_jmhTest.multipleUniformSweepRun_sample_jmhStub(SweepBenchmarks_multipleUniformSweepRun_jmhTest.java:569)
	at com.palantir.atlasdb.performance.benchmarks.generated.SweepBenchmarks_multipleUniformSweepRun_jmhTest.multipleUniformSweepRun_SampleTime(SweepBenchmarks_multipleUniformSweepRun_jmhTest.java:460)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.AssertionError: 
Expected: is <90L>
     but: was <80L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.palantir.atlasdb.performance.benchmarks.SweepBenchmarks.runSingleSweep(SweepBenchmarks.java:48)
	at com.palantir.atlasdb.performance.benchmarks.SweepBenchmarks.batchedUniformSingleSweepRun(SweepBenchmarks.java:82)
	at com.palantir.atlasdb.performance.benchmarks.generated.SweepBenchmarks_batchedUniformSingleSweepRun_jmhTest.batchedUniformSingleSweepRun_sample_jmhStub(SweepBenchmarks_batchedUniformSingleSweepRun_jmhTest.java:569)
	at com.palantir.atlasdb.performance.benchmarks.generated.SweepBenchmarks_batchedUniformSingleSweepRun_jmhTest.batchedUniformSingleSweepRun_SampleTime(SweepBenchmarks_batchedUniformSingleSweepRun_jmhTest.java:460)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tboam** [comment]
Fixed.  Async unlocker sometimes locks the immutable timestamp so we don't sweep what we expect
