### ISSUE TITLE
RejectedExecutionException in PaxosQuorumChecker from 0.105.0

### ISSUE THREAD

**Issue by nartmal** [palantir/atlasdb#3534]
I'm guessing its from https://github.com/palantir/atlasdb/pull/3505

Internally, our ha-embedded smoke tests are flaking very often ( > 50%) due to this exception

```
	"tags": {
	},
	"thread": "dw-134",
	"time": "2018-10-02T01:08:13.704Z",
	"traceId": "451db8cd4c3893a0",
	"type": "service.1",
	"unsafeParams": {
		"throwable0_message": "Task java.util.concurrent.FutureTask@34a9456e rejected from com.palantir.common.concurrent.PTExecutors$1@57d93617[Running, pool size = 100, active threads = 100, queued tasks = 0, completed tasks = 346]"
	}
	"stacktrace": "java.util.concurrent.RejectedExecutionException: {throwable0_message}
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.palantir.common.concurrent.PTExecutors$1.execute(PTExecutors.java:378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at com.codahale.metrics.InstrumentedExecutorService.submit(InstrumentedExecutorService.java:79)
	at com.palantir.common.concurrent.MultiplexingCompletionService.submitAndPrepareForQueueing(MultiplexingCompletionService.java:85)
	at com.palantir.common.concurrent.MultiplexingCompletionService.submit(MultiplexingCompletionService.java:72)
	at com.palantir.paxos.PaxosQuorumChecker.collectResponses(PaxosQuorumChecker.java:178)
	at com.palantir.paxos.PaxosQuorumChecker.collectQuorumResponses(PaxosQuorumChecker.java:94)
	at com.palantir.paxos.PaxosLatestRoundVerifierImpl.collectResponses(PaxosLatestRoundVerifierImpl.java:54)
	at com.palantir.paxos.PaxosLatestRoundVerifierImpl.isLatestRound(PaxosLatestRoundVerifierImpl.java:48)
	at com.palantir.paxos.CoalescingPaxosLatestRoundVerifier$1.lambda$load$0(CoalescingPaxosLatestRoundVerifier.java:37)
	at com.palantir.paxos.CoalescingSupplier.resetAndCompleteIfNotCompleted(CoalescingSupplier.java:67)
	at com.palantir.paxos.CoalescingSupplier.completeOrWaitForCompletion(CoalescingSupplier.java:54)
	at com.palantir.paxos.CoalescingSupplier.get(CoalescingSupplier.java:46)
	at com.palantir.paxos.CoalescingPaxosLatestRoundVerifier.isLatestRound(CoalescingPaxosLatestRoundVerifier.java:47)
	at com.palantir.leader.PaxosLeaderElectionService.determineLeadershipStatus(PaxosLeaderElectionService.java:489)
	at com.palantir.leader.PaxosLeaderElectionService.determineAndRecordLeadershipStatus(PaxosLeaderElectionService.java:471)
	at com.palantir.leader.PaxosLeaderElectionService.isStillLeading(PaxosLeaderElectionService.java:466)
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:145)
	at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:122)
	at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:102)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy73.isStillLeading(Unknown Source)
```

What I am seeing is my service gaining leadership after 25 seconds from jvm starting, then losing it due to RejectedExecutionException after 9 seconds as leader. 

It eventually resolves it self (~3 seconds from the sample docker logs i was tailing), but at that point, we have already failed all our Start-up tasks and the entire service is reporting unhealthly.

**Comment by nartmal** [comment]
rolling back to just 0.104.0 gave me 3/3 successful builds in a row, recently today i was 0/3 in getting a build to pass due to the ha-embedded-smoke-tests we have.

**Comment by nartmal** [comment]
fixed in https://github.com/palantir/atlasdb/pull/3536
