### ISSUE TITLE
NPE when calling getRowsColumnRange

### ISSUE THREAD

**Issue by pkoenig10** [palantir/atlasdb#3743]
This is on 0.116.1.

```
java.lang.NullPointerException: {throwable0_message}
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$3$1.apply(CassandraKeyValueServiceImpl.java:864)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$3$1.apply(CassandraKeyValueServiceImpl.java:835)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithGoodResource(CassandraClientPoolingContainer.java:129)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolingContainer.runWithPooledResource(CassandraClientPoolingContainer.java:105)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithPooledResourceRecordingMetrics(CassandraClientPoolImpl.java:447)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPoolImpl.runWithRetryOnHost(CassandraClientPoolImpl.java:394)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$3.page(CassandraKeyValueServiceImpl.java:832)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$3.getFirstPage(CassandraKeyValueServiceImpl.java:821)
	at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$3.getFirstPage(CassandraKeyValueServiceImpl.java:818)
	at com.palantir.util.paging.AbstractPagingIterable$PagingIterator.computeNext(AbstractPagingIterable.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:140)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:135)
	at com.palantir.common.base.ClosableIterators$1.hasNext(ClosableIterators.java:32)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1331)
	at com.palantir.atlasdb.keyvalue.impl.LocalRowColumnRangeIterator.hasNext(LocalRowColumnRangeIterator.java:34)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1331)
	at com.palantir.atlasdb.keyvalue.impl.LocalRowColumnRangeIterator.hasNext(LocalRowColumnRangeIterator.java:34)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransaction.getRowsColumnRange(SnapshotTransaction.java:380)
	at com.palantir.atlasdb.transaction.impl.ReadTransaction.getRowsColumnRange(ReadTransaction.java:115)
        ...
```

**Comment by sandorw** [comment]
events issue 598
