### ISSUE TITLE
TransactionManager#isInitialized returns true despite not being initialized

### ISSUE THREAD

**Issue by nartmal** [palantir/atlasdb#4689]
From the javadoc:

```
public interface TransactionManager extends AutoCloseable {
    /**
     * Whether this transaction manager has established a connection to the backing store and timestamp/lock services,
     * and is ready to service transactions.
     *
...
     * @return true if and only if the TransactionManager has been fully initialized
     */
    @DoDelegate
    default boolean isInitialized() {
        return true;
    }
```

This lead me to believe, that I could start using my transactionManager when isInitialized returns true, which I explicitly blocked on an internal product that is named after something from the movie The Fifth Element.

Which i tried, but still got a NotInitializedException

see stacktrace below

```
{
	"level": "INFO",
	"message": "TransactionManager is not initialized. Aborting transaction with runTaskWithRetry",
	"origin": "com.palantir.atlasdb.transaction.impl.TransactionRetryStrategy",
	"params": {
	},
	"sid": null,
	"stacktrace": "com.palantir.exception.NotInitializedException: {throwable0_message}
	at com.palantir.async.initializer.AsyncInitializer.checkInitialized(AsyncInitializer.java:135)
	at com.palantir.timestamp.PersistentTimestampServiceImpl$InitializingWrapper.delegate(PersistentTimestampServiceImpl.java:34)
	at com.palantir.timestamp.AutoDelegate_PersistentTimestampService.getFreshTimestamp(AutoDelegate_PersistentTimestampService.java:26)
	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.palantir.leader.proxy.AwaitingLeadershipProxy.handleInvocation(AwaitingLeadershipProxy.java:243)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy86.getFreshTimestamp(Unknown Source)
	at com.palantir.tritium.proxy.InstrumentedTimestampService_ManagedTimestampService_Closeable$6.getFreshTimestamp(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.palantir.atlasdb.factory.LocalOrRemoteProxy.handleInvocation(LocalOrRemoteProxy.java:67)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy88.getFreshTimestamp(Unknown Source)
	at com.palantir.lock.impl.LegacyTimelockService.lockImmutableTimestamp(LegacyTimelockService.java:80)
	at com.palantir.lock.impl.LegacyTimelockService.startIdentifiedAtlasDbTransaction(LegacyTimelockService.java:111)
	at com.palantir.lock.client.TimeLockClient.executeOnTimeLock(TimeLockClient.java:146)
	at com.palantir.lock.client.TimeLockClient.startIdentifiedAtlasDbTransaction(TimeLockClient.java:97)
	at com.palantir.lock.client.ProfilingTimelockService.runTaskTimed(ProfilingTimelockService.java:156)
	at com.palantir.lock.client.ProfilingTimelockService.startIdentifiedAtlasDbTransaction(ProfilingTimelockService.java:111)
	at com.palantir.atlasdb.factory.timelock.TimestampCorroboratingTimelockService.checkAndUpdateLowerBound(TimestampCorroboratingTimelockService.java:74)
	at com.palantir.atlasdb.factory.timelock.TimestampCorroboratingTimelockService.startIdentifiedAtlasDbTransaction(TimestampCorroboratingTimelockService.java:65)
	at com.palantir.atlasdb.transaction.impl.InstrumentedTimelockService.executeWithRecord(InstrumentedTimelockService.java:111)
	at com.palantir.atlasdb.transaction.impl.InstrumentedTimelockService.startIdentifiedAtlasDbTransaction(InstrumentedTimelockService.java:67)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.setupRunTaskWithConditionThrowOnConflict(SnapshotTransactionManager.java:167)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.setupRunTaskWithConditionThrowOnConflict(SerializableTransactionManager.java:62)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.lambda$runTaskWithConditionThrowOnConflict$1(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTimed(SnapshotTransactionManager.java:471)
	at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithConditionThrowOnConflict(SnapshotTransactionManager.java:156)
	at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithConditionThrowOnConflict(SerializableTransactionManager.java:62)
	at com.palantir.atlasdb.transaction.impl.AbstractConditionAwareTransactionManager.lambda$runTaskWithConditionWithRetry$0(AbstractConditionAwareTransactionManager.java:49)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.palantir.atlasdb.transaction.impl.TransactionRetryStrategy.runWithRetry(TransactionRetryStrategy.java:86)
	at com.palantir.atlasdb.transaction.impl.AbstractConditionAwareTransactionManager.runTaskWithConditionWithRetry(AbstractConditionAwareTransactionManager.java:46)
	at com.palantir.tritium.proxy.InstrumentedTransactionManager$12.runTaskWithConditionWithRetry(Unknown Source)
	at com.palantir.atlas.migration2.api.MigrationAwareTransactionManagerImpl.runTaskWithSchemaVersionWithRetry(MigrationAwareTransactionManagerImpl.java:131)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by pkoenig10** [comment]
I think this class is the problem:
https://github.com/palantir/atlasdb/blob/2936f29213806e0c8ffb174dc7c9735ce0a6ee2d/lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java#L189-L208

It's used to wrap the `TimelockService` but doesn't override the default implementation of `isInitialized`:
https://github.com/palantir/atlasdb/blob/2936f29213806e0c8ffb174dc7c9735ce0a6ee2d/timestamp-api/src/main/java/com/palantir/timestamp/TimestampService.java#L47-L49

So this line will return `true` even though the underlying `PersistentTimestampServiceImpl` is not initialized:
https://github.com/palantir/atlasdb/blob/2936f29213806e0c8ffb174dc7c9735ce0a6ee2d/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java#L163

**Comment by pkoenig10** [comment]
I think this issue is caused by the [`ProfilingTimelockService`](https://github.com/palantir/atlasdb/blob/1e67ca1a06de5e353833794f86fc6151bba0e23b/lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java). This wraps the `TimeLockClient` used in the transaction manager.
https://github.com/palantir/atlasdb/blob/ad81a3446c04874106f86163e8ab89b1bc997e1d/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L869

But `ProfilingTimelockService` does not override `isInitialized` to delegate to the `TimeLockClient`. So the transaction manager thinks the timelock and timestamp service are initialized even though the underlying implementation is not.
https://github.com/palantir/atlasdb/blob/ad81a3446c04874106f86163e8ab89b1bc997e1d/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java#L162-L163
