### ISSUE TITLE
Duplicate TimestampService metrics

### ISSUE THREAD

**Issue by pkoenig10** [palantir/atlasdb#4927]
Atlas creates duplicate `TimestampService` metrics which causes problems with the `DisjointUnionTaggedMetricSet`. This error occurs on 0.239.10, even after https://github.com/palantir/atlasdb/pull/4921.
```
java.lang.IllegalArgumentException: Multiple entries with same key: MetricName{safeName=com.palantir.timestamp.TimestampService.getFreshTimestamp, safeTags={}}=com.codahale.metrics.Timer@460c003c and MetricName{safeName=com.palantir.timestamp.TimestampService.getFreshTimestamp, safeTags={}}=com.codahale.metrics.Timer@110af4b7
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:394)
	at com.palantir.atlasdb.metrics.DisjointUnionTaggedMetricSet.getMetrics(DisjointUnionTaggedMetricSet.java:44)
	at com.palantir.atlasdb.metrics.FilteredTaggedMetricSet.getMetrics(FilteredTaggedMetricSet.java:47)
	at com.palantir.tritium.metrics.registry.AbstractTaggedMetricRegistry.lambda$getMetrics$5(AbstractTaggedMetricRegistry.java:181)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at com.palantir.tritium.metrics.registry.AbstractTaggedMetricRegistry.getMetrics(AbstractTaggedMetricRegistry.java:181)
```

I presume these duplicate metrics are because we are instrument `TimestampService` in multiple places. It appears that we instrument `TimestampService` at:
https://github.com/palantir/atlasdb/blob/3290b9f6b2ae720f1d2733bb65c6d72c025d103d/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L1198-L1201
https://github.com/palantir/atlasdb/blob/3290b9f6b2ae720f1d2733bb65c6d72c025d103d/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L1220

**Comment by Jolyon-S** [comment]
Does this still occur on `0.240.0`?

**Comment by pkoenig10** [comment]
Yes, see this internal CI build:
https://c.p.b/gh/f/multipass/208865/artifacts/0/home/circleci/artifacts/dockerLogs/multipass-standard/multipass.log

**Comment by pkoenig10** [comment]
I've confirmed that the lines I posted in the PR description are the cause of this problem.

The `DisjointUnionTaggedMetricSet` is concerning since it's incredibly easy to accidentally introduce duplicate metrics names if you create a tagged metrics without any tags.
