### ISSUE TITLE
SSL Issues Should Log As Such

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#516]
Per QA-95061 and my own experience, ssl issues on startup don't actually log as ssl issues and we should make it clearer.  The current error message you will see is as follows:

```
java.lang.RuntimeException: org.apache.thrift.TException: No host tried was able to create the keyspace requested.
    at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runOneTimeStartupChecks(CassandraClientPool.java:254)
    at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.init(CassandraKeyValueService.java:171)
    at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.create(CassandraKeyValueService.java:157)
    at com.palantir.nexus.db.prefs.CassandraKvsFactory.createKvs(CassandraKvsFactory.java:41)
    at com.palantir.nexus.db.prefs.KeyValueServiceFactories.createKvs(KeyValueServiceFactories.java:31)
    at com.palantir.metropolis.cli.AtlasDBKvsPreferencesCli$3.run(AtlasDBKvsPreferencesCli.java:202)
    at com.palantir.metropolis.cli.AtlasDBKvsPreferencesCli$OperationsCollector.finish(AtlasDBKvsPreferencesCli.java:122)
    at com.palantir.metropolis.cli.AtlasDBKvsPreferencesCli.execute(AtlasDBKvsPreferencesCli.java:322)
    at com.palantir.common.console.AbstractCommandLineUtility.run(AbstractCommandLineUtility.java:159)
    at com.palantir.util.PalantirAbstractCommandLineUtility.run(PalantirAbstractCommandLineUtility.java:100)
    at com.palantir.util.ServerCommandLineUtility.run(ServerCommandLineUtility.java:72)
    at com.palantir.metropolis.cli.AtlasDBKvsPreferencesCli.main(AtlasDBKvsPreferencesCli.java:48)
Caused by: org.apache.thrift.TException: No host tried was able to create the keyspace requested.
    at com.palantir.atlasdb.keyvalue.cassandra.CassandraVerifier.ensureKeyspaceExistsAndIsUpToDate(CassandraVerifier.java:169)
    at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runOneTimeStartupChecks(CassandraClientPool.java:251)
    ... 11 more
```

**Comment by tpetracca** [comment]
Related is #215.  Assigning to myself.

**Comment by clockfort** [comment]
you should also get a "couldn't use host {host} to create keyspace, it returned exception {the actual exception that says SSL failed} during the attempt". Maybe we could return the last exception encountered as part of the final TException("No host tried was able to create the keyspace requested.") just so it bubbles up to the top and people don't even have to read the logs and can just see from whatever application they're in.

**Comment by clockfort** [comment]
(we resolved tomk's error by him looking in his cli log and seeing all of the SSL errors)

**Comment by tpetracca** [comment]
When I hit this issue testing atlas-cli off develop earlier this week one
of my issues boiled down to SSL and I never actually got the SSL exception
at the bottom, however this was me printing the encountered error to
System.err when caught by AtlasCli because there is not logging setup
created when your run the cli (which is a separate issue we need to
address).

**Comment by clockfort** [comment]
Yeah, adding "last seen exception from client" to the final TException actually thrown should have the effect of telling even people who do that behavior that it's an SSL issue.

**Comment by jboreiko** [comment]
Hey @tpetracca can we get an update on the progress or a PR associated with it?

**Comment by rhero** [comment]
We're going to try and give a log message that enumerates the most common root causes of this error.

**Comment by rhero** [comment]
@tpetracca do you think this issue is worth keeping open? Given configs are being managed by services and everything is defaulting to SSL, I'm not sure we're actually going to ever get to this.
