### ISSUE TITLE
Misconfigured Paxos errors confusing

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#550]
Seen on internal ticket PDS-43887

WARN [2016-06-09 01:01:17,107] leadership: Leadership was not gained
! com.palantir.paxos.PaxosRoundFailureException: failed to acquire quorum in paxos phase one
! at com.palantir.paxos.PaxosProposerImpl.phaseOne(PaxosProposerImpl.java:158) ~[leader-election-impl-0.6.0.jar:na]
! at com.palantir.paxos.PaxosProposerImpl.propose(PaxosProposerImpl.java:89) ~[leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.PaxosLeaderElectionService.proposeLeadership(PaxosLeaderElectionService.java:343) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.PaxosLeaderElectionService.blockOnBecomingLeader(PaxosLeaderElectionService.java:140) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy.gainLeadership(AwaitingLeadershipProxy.java:106) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy.access$000(AwaitingLeadershipProxy.java:45) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy$1.run(AwaitingLeadershipProxy.java:94) [leader-election-impl-0.6.0.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
! at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55) [commons-executors-0.6.0.jar:na]
! at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486) [commons-executors-0.6.0.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
WARN [2016-06-09 01:01:17,108] com.palantir.leader.PaxosLeaderElectionService: unable to get uuid from server

The result of the support ticket was a misconfigured leader block that lead to none of the hosts able to reach the others.  Would be valuable if the error here was clearer to reduce debugging time for engineers in the field.

**Comment by jboreiko** [comment]
Move message to info and remove stack trace.
