### ISSUE TITLE
Should not output an unusable error message when we use the documented config

### ISSUE THREAD

**Issue by gbrova** [palantir/atlasdb#784]
The current setup points at http:// servers with ssl enabled.

**Comment by hsaraogi** [comment]
More context from Adi.

1. The leader block requires you to specify the hostname, port, context path and protocol in the URIs. The protocol(http/https) can be inferred from if we use SSL or not. Alternatively, we can just have an optional “disableSSL” flag and default to false.
2. Accidentally specifying http://hostname with SSL enabled on the server, results in a totally cryptic error:

```
WARN  [2016-08-15 13:44:52,397] com.palantir.atlasdb.http.FailoverFeignTarget: This connection has tried 14 hosts each 3 times and has failed out.
! java.io.EOFException: \n not found: size=0 content=…
! at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215) ~[okio-1.8.0.jar:na]
! at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[okhttp-2.7.0.jar:na]
! ... 53 common frames omitted
! Causing: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@b5bc523a
! at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:739) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:724) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:578) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.Call.getResponse(Call.java:287) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.0.jar:na]
! at com.squareup.okhttp.Call.execute(Call.java:80) ~[okhttp-2.7.0.jar:na]
! at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:154) ~[feign-okhttp-8.15.0.jar:8.15.0]
! at com.palantir.atlasdb.http.FailoverFeignTarget$1.execute(FailoverFeignTarget.java:177) ~[atlasdb-config-0.11.2.jar:na]
! at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:95) ~[feign-core-8.15.0.jar:8.15.0]
! ... 41 common frames omitted
```

- There was just one host, why 14 hosts?
- EOF exception?
- Why is the exception message cut off abruptly?
- Why is this logged at WARN. The server is totally unusable — this should at the very least be an ERROR.

**Comment by hsaraogi** [comment]
There is no repro for this error, seems that this was a one off case.

Atas Client does start up with ssl enabled and the leaderblock having servers with http.

Any requests using the client however fail with:

```
feign.RetryableException: Connection refused executing POST http://192.168.99.100:32888/todos/

	at feign.FeignException.errorExecuting(FeignException.java:56)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy14.addTodo(Unknown Source)
	at com.palantir.atlasdb.ete.todo.TodoEteTest.shouldBeAbleToWriteAndListTodos(TodoEteTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
	at com.squareup.okhttp.Connection.connectSocket(Connection.java:196)
	at com.squareup.okhttp.Connection.connect(Connection.java:172)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
	at com.squareup.okhttp.Call.getResponse(Call.java:267)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:153)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
	... 42 more
etryableexception: Connection refused executing POST http://192.168.99.100:32888/todos/at feign.FeignException.errorExecuting(FeignException.java:56)at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)at com.sun.proxy.$Proxy14.addTodo(Unknown Source)at com.palantir.atlasdb.ete.todo.TodoEteTest.shouldBeAbleToWriteAndListTodos(TodoEteTest.java:41)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)at org.junit.rules.RunRules.evaluate(RunRules.java:20)at org.junit.runners.ParentRunner.run(ParentRunner.java:363)at org.junit.runners.Suite.runChild(Suite.java:128)at org.junit.runners.Suite.runChild(Suite.java:27)at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)at org.junit.runners.ParentRunner.run(ParentRunner.java:363)at org.junit.runner.JUnitCore.run(JUnitCore.java:137)at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)Caused by: java.net.ConnectException: Connection refusedat java.net.PlainSocketImpl.socketConnect(Native Method)at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)at java.net.Socket.connect(Socket.java:589)at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)at com.squareup.okhttp.Connection.connectSocket(Connection.java:196)at com.squareup.okhttp.Connection.connect(Connection.java:172)at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)at com.squareup.okhttp.Call.getResponse(Call.java:267)at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)at com.squareup.okhttp.Call.execute(Call.java:79)at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:153)at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)... 42 more


``` 

The requests fail, which is expected. It would be nice to infer the protocol from the ssl. That can be prioritized accordingly.

**Comment by tpetracca** [comment]
@hsaraogi can you confirm my theory around how SSL is configured for Paxos communication?  And regardless of the error it sounds like we need better javadocs/documentation around how it's configured to increase clarity for our consumers.

**Comment by hsaraogi** [comment]
@tpetracca : you mentioned that the SSLSocketfactory specifies the SSL settings, that is partially correct. Whether ssl is configured or not depends on the server block in config. I used this block for testing:

```
server:
#  adminContextPath: /
  adminMaxThreads: 128
  adminConnectors:
    - type: https
      port: 3828
      bindHost: localhost
      allowRenegotiation: false
      excludedProtocols: [SSLv3]
      certAlias: private-server
      keyStorePath: /Users/hsaraogi/keyStore.jks
      keyStorePassword: keystore
      validateCerts: false
#  applicationContextPath: /multipass
  applicationConnectors:
    - type: https
      port: 3829
      allowRenegotiation: false
      excludedProtocols: [SSLv3]
      certAlias: private-server
      keyStorePath: /Users/hsaraogi/keyStore.jks
      keyStorePassword: keystore
      validateCerts: false
  rootPath: /api/*
```

I have a PR #813 that makes the logging slightly better. It would be nice if you could review.

**Comment by tpetracca** [comment]
So I guess my point is that, that config is specifically for how our internal dropwizard applications specify their server ssl configuration.  They then just happen to choose to pass their own server ssl config to the TransactionManagers.create() method which is why you're seeing the behavior you're seeing.

**Comment by hsaraogi** [comment]
Answering questions in the issue:

- There  was just one host, why 14 hosts?
We roll among the hosts and try 14 times. Basically try each
server 3 times and loop through them and add some backoff each time you
visit a new server.  This should be like 30 - 40s which by the time the
server comes back up the client doesn't barf. (tuned in 2009).

- Why EOF exception?
Known issue in [square/okhttp](https://github.com/square/okhttp/issues/1114). Its due to reading from the response body and parsing for '\n'-s.

- Why is the exception message cut off abruptly?
identical stack trace lines are omitted in general.

- Why is this logged at WARN. The server is totally unusable — this should at the very least be an ERROR.
 It should be an ERROR and the message about the failure should be clearer.

**Comment by hsaraogi** [comment]
Improved some logging around this. Closing because we are not likely to hit the SSL error in field.
