### ISSUE TITLE
AtlasDB clients report confusing error on startup if Cassandra is slow to start

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#800]
An internal stack was running multiple AtlasDB clients and restarted all of the services at the same time. While the AtlasDB clients were starting there were cryptic error messages, and the resolution was to just wait a little bit for Cassandra to start.

We should improve this message.

```
ERROR [2016-08-16 17:00:02,761] com.palantir.atlasdb.keyvalue.cassandra.CassandraVerifier: Couldn't use host <hostname>:<port> to create keyspace, it returned exception "InvalidRequestException(why:Keyspace names must be case-insensitively unique ("<keyspace>" conflicts with "<keyspace>"))" during the attempt.
! org.apache.cassandra.thrift.InvalidRequestException: null
! at org.apache.cassandra.thrift.Cassandra$system_add_keyspace_result$system_add_keyspace_resultStandardScheme.read(Cassandra.java:44882) ~[cassandra-thrift-2.2.1.jar:2.2.1]
! at org.apache.cassandra.thrift.Cassandra$system_add_keyspace_result$system_add_keyspace_resultStandardScheme.read(Cassandra.java:44860) ~[cassandra-thrift-2.2.1.jar:2.2.1]
! at org.apache.cassandra.thrift.Cassandra$system_add_keyspace_result.read(Cassandra.java:44794) ~[cassandra-thrift-2.2.1.jar:2.2.1]
! at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.9.2.jar:0.9.2]
! at org.apache.cassandra.thrift.Cassandra$Client.recv_system_add_keyspace(Cassandra.java:1580) ~[cassandra-thrift-2.2.1.jar:2.2.1]
! at org.apache.cassandra.thrift.Cassandra$Client.system_add_keyspace(Cassandra.java:1567) ~[cassandra-thrift-2.2.1.jar:2.2.1]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraVerifier.ensureKeyspaceExistsAndIsUpToDate(CassandraVerifier.java:157) ~[atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool.runOneTimeStartupChecks(CassandraClientPool.java:288) [atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.init(CassandraKeyValueService.java:177) [atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService.create(CassandraKeyValueService.java:163) [atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.cassandra.CassandraAtlasDbFactory.createKv(CassandraAtlasDbFactory.java:41) [atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.cassandra.CassandraAtlasDbFactory.createRawKeyValueService(CassandraAtlasDbFactory.java:37) [atlasdb-cassandra-0.10.0.jar:na]
! at com.palantir.atlasdb.factory.ServiceDiscoveringAtlasSupplier.lambda$new$1(ServiceDiscoveringAtlasSupplier.java:47) [atlasdb-config-0.10.0.jar:na]
! at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125) ~[guava-18.0.jar:na]
```
Internal ticket is PDS-44921.

**Comment by gsheasby** [comment]
So the specific message quoted has been squashed (commit hash , which merged in 0.11.0), but other flavours of this error appeared in internal logs and would not have been caught by the 0.11.0 fix. In these cases, we intend to bump down the severity, and log the stack traces at the TRACE level.
