### ISSUE TITLE
Invalid leader config does not timeout

### ISSUE THREAD

**Issue by harishutd** [palantir/atlasdb#884]
I had wrong urls in my leader config and atlas just kept trying to do leader election indefinitely with the following logs:

WARN  [2016-09-01 12:03:08,212] com.palantir.paxos.PaxosQuorumChecker: We encountered an error while trying to request an acknowledgement from another paxos node. This could mean the node is down, or we cannot connect to it for some other reason.
! feign.FeignException: status 404 reading PaxosLearner#getLearnedValuesSince(long); content:
! <html>
! <head>
! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
! <title>Error 404 Not Found</title>
! </head>
! <body><h2>HTTP ERROR 404</h2>
! <p>Problem accessing /salt/learner/learned-values-since/0. Reason:
! <pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
!
! </body>
! </html>
!
! at feign.FeignException.errorStatus(FeignException.java:62) ~[feign-core-8.16.0.jar:8.16.0]
! at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91) ~[feign-core-8.16.0.jar:8.16.0]
! at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:126) ~[feign-core-8.16.0.jar:8.16.0]
! at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74) ~[feign-core-8.16.0.jar:8.16.0]
! at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-8.16.0.jar:8.16.0]
! at com.sun.proxy.$Proxy58.getLearnedValuesSince(Unknown Source) ~[na:na]
! at com.palantir.leader.PaxosLeaderElectionService$4.apply(PaxosLeaderElectionService.java:598) ~[leader-election-impl-0.12.0.jar:na]
! at com.palantir.leader.PaxosLeaderElectionService$4.apply(PaxosLeaderElectionService.java:593) ~[leader-election-impl-0.12.0.jar:na]
! at com.palantir.paxos.PaxosQuorumChecker$1.call(PaxosQuorumChecker.java:80) ~[leader-election-impl-0.12.0.jar:na]
! at com.palantir.paxos.PaxosQuorumChecker$1.call(PaxosQuorumChecker.java:77) ~[leader-election-impl-0.12.0.jar:na]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_92]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_92]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_92]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
WARN  [2016-09-01 12:03:08,212] com.palantir.paxos.PaxosQuorumChecker: We encountered an error while trying to request an acknowledgement from another paxos node. This could mean the node is down, or we cannot connect to it for some other reason.
! feign.FeignException: status 404 reading PaxosLearner#getLearnedValuesSince(long); content:
! <html>
! <head>
! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
! <title>Error 404 Not Found</title>
! </head>
! <body><h2>HTTP ERROR 404</h2>
! <p>Problem accessing /salt/learner/learned-values-since/0. Reason:
! <pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
!
! </body>
! </html>

**Comment by gsheasby** [comment]
Two solutions:
low-lift: improve error message
higher lift: fail out after multiple successive 404s are received.

@harishutd is this still bothering you?

**Comment by harishutd** [comment]
@gsheasby would be nice to time out eventually and fail

**Comment by tpetracca** [comment]
this goes away with external timelock
