### ISSUE TITLE
Remove references to dispatch from dbkvs

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#993]
We shouldn't be logging errors referencing dispatch as that is product specific and confusing. Example:

```
ERROR [2016-09-23 20:41:59,860] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 811bd4a4b30ca06d
! com.palantir.timestamp.MultipleRunningTimestampServiceError: Timestamp limit changed underneath us (limit in memory: 46126139, limit in DB: 47126145). This may indicate that an
other timestamp service is running against this database!  If you get this error check that your client.prefs in dispatch is configured correctly.
! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore$1.run(InDbTimestampBoundStore.java:95) ~[atlasdb-dbkvs-0.12.0.jar:na]
! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore$1.run(InDbTimestampBoundStore.java:84) ~[atlasdb-dbkvs-0.12.0.jar:na]
! at com.palantir.nexus.db.pool.RetriableTransactions$1LexicalHelper.attemptTx(RetriableTransactions.java:191) ~[commons-db-0.12.0.jar:na]
! at com.palantir.nexus.db.pool.RetriableTransactions$1LexicalHelper.run(RetriableTransactions.java:147) ~[commons-db-0.12.0.jar:na]
! at com.palantir.nexus.db.pool.RetriableTransactions.run(RetriableTransactions.java:249) ~[commons-db-0.12.0.jar:na]
! at com.palantir.atlasdb.keyvalue.dbkvs.timestamp.InDbTimestampBoundStore.runOperation(InDbTimestampBoundStore.java:84) ~[atlasdb-dbkvs-0.12.0.jar:na]
! ... 85 common frames omitted

```

**Comment by hsaraogi** [comment]
#981 is the PR.
